export interface Project {
  project_id: number;
  partner_image: string;
  partner_name: string;
  project_name: string;
  project_desc: string;
  tags: string[];
  collaborators: {
    name: string;
    image?: string | null;
  }[];
  progress: number;
  started_at: string;
  deadline: string;
}

export const projectsList: Project[] = [
    {
        project_id: 1,
        partner_image: "/images/logos/google.svg",
        partner_name: "سامسونگ",
        project_name: "کدکس",
        project_desc: "یک پلتفرم برای برنامه‌نویسی گروهی و اشکال‌زدایی مشترک",
        tags: ["واقعیت مجازی", "رباتیک"],
        collaborators: [
            { name: "ادسل دیون", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 19,
        started_at: "8/10/2022",
        deadline: "8/10/2023",
    },
    {
        project_id: 2,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "اچ‌پی",
        project_name: "دیتاوایز",
        project_desc:
            "ابزاری برای ایجاد بصری‌سازی داده‌ها و داشبوردهای تعاملی",
        tags: ["آموزش فناوری اطلاعات", "واقعیت افزوده", "هوش مصنوعی"],
        collaborators: [
            { name: "هووارد مسر", image: "/images/avatar/avatar-15.jpg" },
            { name: "آلیسا شال‌کراس", image: "/images/avatar/avatar-3.jpg" },
            { name: "ماریکا کاتز", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 64,
        started_at: "11/13/2022",
        deadline: "12/13/2022",
    },
    {
        project_id: 3,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "سونی",
        project_name: "خانه هوشمند",
        project_desc:
            "سیستمی برای کنترل و مانیتورینگ دستگاه‌های هوشمند خانه",
        tags: ["توسعه وب", "واقعیت مجازی", "علم داده"],
        collaborators: [
            { name: "فرانسیس لیبل", image: "/images/avatar/avatar-19.jpg" },
            { name: "دانی بوزر", image: "/images/avatar/avatar-14.jpg" },
            { name: "ابی اکس‌آپ", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 12,
        started_at: "3/25/2023",
        deadline: "2/25/2024",
    },
    {
        project_id: 4,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "لنوو",
        project_name: "امنیت سایبری",
        project_desc:
            "سیستمی برای کنترل و مانیتورینگ دستگاه‌های هوشمند خانه",
        tags: ["بلاک‌چین", "رباتیک"],
        collaborators: [{ name: "Marlin", image: undefined }],
        progress: 0,
        started_at: "1/7/2023",
        deadline: "9/7/2023",
    },
    {
        project_id: 5,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "هواوی",
        project_name: "چت‌بات",
        project_desc: "چت‌باتی که می‌تواند به سؤالات پاسخ دهد و راهنمایی ارائه کند",
        tags: ["مشاوره فناوری اطلاعات", "اینترنت اشیا"],
        collaborators: [
            { name: "هسکل توث", image: "/images/avatar/avatar-15.jpg" },
            { name: "jorni", image: undefined },
        ],
        progress: 86,
        started_at: "11/19/2022",
        deadline: "10/19/2023",
    },
    {
        project_id: 6,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "اپل",
        project_name: "ایر",
        project_desc:
            "یک سیستم هوش مصنوعی که می‌تواند فرمان‌های صوتی را تشخیص داده و به آن‌ها پاسخ دهد",
        tags: ["طراحی رابط کاربری"],
        collaborators: [
            { name: "لینت اوشییرین", image: "/images/avatar/avatar-16.jpg" },
            { name: "ولاد متیاتین", image: "/images/avatar/avatar-15.jpg" },
            { name: "فارا دیدام", image: "/images/avatar/avatar-18.jpg" },
            { name: "اینگرید کانوری", image: "/images/avatar/avatar-1.jpg" },
            { name: "dank", image: undefined },
        ],
        progress: 100,
        started_at: "6/11/2022",
        deadline: "8/11/2022",
    },
    {
        project_id: 7,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "ایسر",
        project_name: "وب‌دِو",
        project_desc:
            "ابزاری برای ساخت و میزبانی وب‌سایت‌های شخصی",
        tags: ["اتوماسیون", "اینترنت اشیا"],
        collaborators: [
            { name: "سوزان بوتمن", image: "/images/avatar/avatar-1.jpg" },
            { name: "جکی همیلتون", image: "/images/avatar/avatar-8.jpg" },
            { name: "جوزف وهنر", image: "/images/avatar/avatar-17.jpg" },
            { name: "درونا درگان", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 61,
        started_at: "5/19/2022",
        deadline: "5/19/2023",
    },
    {
        project_id: 8,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "هواوی",
        project_name: "کلودی",
        project_desc:
            "سرویس رایانش ابری که ذخیره‌سازی، پردازش و منابع شبکه را ارائه می‌دهد",
        tags: ["یادگیری ماشین", "اتوماسیون"],
        collaborators: [
            { name: "ادگار کونیک", image: "/images/avatar/avatar-13.jpg" },
            { name: "آنتونی دومنین", image: "/images/avatar/avatar-20.jpg" },
            { name: "گودارد برنوزی", image: "/images/avatar/avatar-15.jpg" },
            { name: "درک گریواستون", image: "/images/avatar/avatar-17.jpg" },
            { name: "استاوروس تردول", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 77,
        started_at: "8/13/2022",
        deadline: "12/13/2022",
    },
    {
        project_id: 9,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سونی",
        project_name: "وی‌آر‌وای",
        project_desc:
            "یک اپ واقعیت مجازی که به شما امکان می‌دهد محیط‌های غوطه‌ور را کاوش و ایجاد کنید",
        tags: ["اتوماسیون", "بازی‌سازی", "علم داده"],
        collaborators: [
            { name: "رزاموند مولر", image: "/images/avatar/avatar-14.jpg" },
            { name: "ند مک‌گرین", image: "/images/avatar/avatar-3.jpg" },
            { name: "جویوس بریگدیل", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 8,
        started_at: "12/3/2022",
        deadline: "6/3/2023",
    },
    {
        project_id: 10,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "سونی",
        project_name: "آی‌اوتایز",
        project_desc: "دستگاهی که هر شیئی را به اینترنت اشیا متصل می‌کند",
        tags: ["مدیریت سیستم"],
        collaborators: [
            { name: "شینا اسکریور", image: "/images/avatar/avatar-16.jpg" },
            { name: "تدی والکار", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 77,
        started_at: "9/3/2022",
        deadline: "7/3/2023",
    },
    {
        project_id: 11,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "اچ‌پی",
        project_name: "زیست‌فناوری",
        project_desc:
            "پروژه زیست‌فناوری که از موجودات زنده یا اجزای آن‌ها برای اهداف مختلف استفاده می‌کند",
        tags: ["توسعه وب", "مدیریت سیستم"],
        collaborators: [
            { name: "A.Fadaei", image: undefined },
            { name: "فرح جیامیتی", image: "/images/avatar/avatar-11.jpg" },
            { name: "آلیس دیسلی", image: "/images/avatar/avatar-17.jpg" },
            { name: "Fadaei", image: undefined },
            { name: "Taghipoor", image: undefined },
        ],
        progress: 14,
        started_at: "10/14/2022",
        deadline: "7/14/2023",
    },
    {
        project_id: 12,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "دل",
        project_name: "گیم‌آن",
        project_desc:
            "استودیوی بازی‌سازی که به توسعه و انتشار بازی‌های ویدیویی می‌پردازد",
        tags: ["توسعه وب"],
        collaborators: [
            { name: "کریسی دشوود", image: "/images/avatar/avatar-16.jpg" },
            { name: "آکیم پرونّی", image: "/images/avatar/avatar-9.jpg" },
            { name: "سالیوان اسپلین", image: "/images/avatar/avatar-2.jpg" },
            { name: "بِوِن کیریما", image: "/images/avatar/avatar-2.jpg" },
        ],
        progress: 5,
        started_at: "8/5/2022",
        deadline: "6/5/2023",
    },
    {
        project_id: 13,
        partner_image: "/images/logos/google.svg",
        partner_name: "اچ‌پی",
        project_name: "ادوتک",
        project_desc:
            "پروژه فناوری آموزشی که فرآیند آموزش و یادگیری را بهبود می‌بخشد",
        tags: ["آموزش فناوری اطلاعات", "توسعه اپلیکیشن موبایل"],
        collaborators: [
            { name: "Reza", image: undefined },
            { name: "جکلین رادی", image: "/images/avatar/avatar-18.jpg" },
            { name: "درک مانسون", image: "/images/avatar/avatar-19.jpg" },
            { name: "تِرِزینا گوکلر", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 58,
        started_at: "10/8/2022",
        deadline: "3/8/2023",
    },
    {
        project_id: 14,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "ال‌جی",
        project_name: "فین‌تک",
        project_desc:
            "پروژه فناوری مالی که راه‌حل‌های نوآورانه‌ای برای بانکداری و امور مالی ارائه می‌کند",
        tags: ["توسعه وب"],
        collaborators: [{ name: "Ali", image: undefined }],
        progress: 20,
        started_at: "12/17/2022",
        deadline: "9/17/2023",
    },
    {
        project_id: 15,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "لنوو",
        project_name: "سلامت‌آی‌تی",
        project_desc:
            "پروژه فناوری اطلاعات سلامت که موجب بهبود ارائه و نتایج مراقبت‌های بهداشتی می‌شود",
        tags: ["امنیت سایبری", "بلاک‌چین", "هوش مصنوعی"],
        collaborators: [
            { name: "روری مریتون", image: "/images/avatar/avatar-15.jpg" },
            { name: "Babak", image: undefined },
            { name: "مارسیل بردزلی", image: "/images/avatar/avatar-16.jpg" },
            { name: "تالیا اسکیونس", image: "/images/avatar/avatar-12.jpg" },
            { name: "سرژ پریشیت", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 54,
        started_at: "1/15/2023",
        deadline: "9/15/2023",
    },
    {
        project_id: 16,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "مایکروسافت",
        project_name: "آی‌تی سبز",
        project_desc:
            "پروژه رمزارز که از فناوری بلاک‌چین برای پرداخت‌های امن بهره می‌برد",
        tags: ["بلاک‌چین", "هوش مصنوعی", "طراحی رابط کاربری"],
        collaborators: [
            { name: "Davod", image: undefined },
            { name: "Hashem", image: undefined },
            { name: "کورالین گنریخ", image: "/images/avatar/avatar-1.jpg" },
            { name: "Amir", image: undefined },
        ],
        progress: 2,
        started_at: "5/13/2022",
        deadline: "2/13/2023",
    },
    {
        project_id: 17,
        partner_image: "/images/logos/google.svg",
        partner_name: "سامسونگ",
        project_name: "شبکه اجتماعی",
        project_desc:
            "پروژه فناوری زیست‌محیطی که بر پایداری و کاهش اثرات محیط‌زیستی تمرکز دارد",
        tags: ["طراحی گرافیک"],
        collaborators: [
            { name: "مایر هیکی", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 90,
        started_at: "5/27/2022",
        deadline: "5/27/2023",
    },
    {
        project_id: 18,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "هواوی",
        project_name: "تجارت الکترونیک",
        project_desc:
            "پروژه شبکه اجتماعی که مردم و جوامع را به هم متصل می‌کند",
        tags: ["تجارت الکترونیک"],
        collaborators: [
            { name: "لایل کانتر", image: "/images/avatar/avatar-7.jpg" },
            { name: "ننی میسی", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 37,
        started_at: "8/21/2022",
        deadline: "10/21/2022",
    },
    {
        project_id: 19,
        partner_image: "/images/logos/google.svg",
        partner_name: "هواوی",
        project_name: "مدیالَب",
        project_desc:
            "پروژه تجارت الکترونیک که به فروش محصولات یا خدمات آنلاین می‌پردازد",
        tags: ["یادگیری ماشین", "طراحی رابط کاربری"],
        collaborators: [
            { name: "دلفین ناپولیونه", image: "/images/avatar/avatar-2.jpg" },
            { name: "ملسا کاتریج", image: "/images/avatar/avatar-17.jpg" },
        ],
        progress: 50,
        started_at: "6/27/2022",
        deadline: "6/27/2023",
    },
    {
        project_id: 20,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "اپل",
        project_name: "کدکس",
        project_desc:
            "پروژه تولید محتوای رسانه‌ای که به ایجاد و توزیع محتوای دیجیتال می‌پردازد",
        tags: ["امنیت سایبری", "طراحی تجربه کاربری", "پشتیبانی فنی"],
        collaborators: [
            { name: "Alis", image: undefined },
            { name: "Ali", image: undefined },
            { name: "کارول مک‌گری", image: "/images/avatar/avatar-18.jpg" },
        ],
        progress: 48,
        started_at: "10/2/2022",
        deadline: "12/2/2022",
    },
    {
        project_id: 21,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "اچ‌پی",
        project_name: "دیتاوایز",
        project_desc: "پلتفرمی برای برنامه‌نویسی گروهی و اشکال‌زدایی مشترک",
        tags: ["امنیت سایبری", "بازاریابی دیجیتال", "بلاک‌چین"],
        collaborators: [
            { name: "برکی ابنیزر", image: "/images/avatar/avatar-7.jpg" },
            { name: "Reza", image: undefined },
            { name: "ولفی لولین", image: "/images/avatar/avatar-1.jpg" },
            { name: "استار مک‌گیلویری", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 89,
        started_at: "1/5/2023",
        deadline: "1/5/2024",
    },
    {
        project_id: 22,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "ایسر",
        project_name: "خانه هوشمند",
        project_desc:
            "ابزاری برای ایجاد بصری‌سازی داده‌ها و داشبوردهای تعاملی",
        tags: ["شبکه‌های اجتماعی", "حسابرسی فناوری اطلاعات", "امنیت سایبری"],
        collaborators: [
            { name: "Ali", image: undefined },
            { name: "الروی رادوس", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 63,
        started_at: "8/23/2022",
        deadline: "5/23/2023",
    },
    {
        project_id: 23,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "ریزر",
        project_name: "امنیت سایبری",
        project_desc:
            "سیستمی برای کنترل و مانیتورینگ دستگاه‌های هوشمند خانه",
        tags: ["حاکمیت فناوری اطلاعات و استراتژی فناوری اطلاعات", "علم داده"],
        collaborators: [{ name: "لورین فاتورینی", image: undefined }],
        progress: 94,
        started_at: "10/26/2022",
        deadline: "5/26/2023",
    },
    {
        project_id: 24,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "نینتندو",
        project_name: "چت‌بات",
        project_desc:
            "سیستمی برای کنترل و مانیتورینگ دستگاه‌های هوشمند خانه",
        tags: ["علم داده", "رایانش ابری", "واقعیت مجازی"],
        collaborators: [
            { name: "فیلیپ نایسمیت", image: "/images/avatar/avatar-8.jpg" },
            { name: "Ahmad", image: undefined },
        ],
        progress: 86,
        started_at: "8/31/2022",
        deadline: "11/30/2022",
    },
    {
        project_id: 25,
        partner_image: "/images/logos/google.svg",
        partner_name: "اپل",
        project_name: "ایر",
        project_desc: "چت‌باتی که می‌تواند به سؤالات پاسخ دهد و راهنمایی ارائه کند",
        tags: ["مهندسی نرم‌افزار", "اینترنت اشیا", "اتوماسیون"],
        collaborators: [
            { name: "کرک د کورسی", image: "/images/avatar/avatar-3.jpg" },
            { name: "Arad", image: undefined },
            { name: "دودی داربیشایر", image: "/images/avatar/avatar-9.jpg" },
            { name: "گیف ویسلکرفت", image: "/images/avatar/avatar-6.jpg" },
            { name: "Ali", image: undefined },
        ],
        progress: 34,
        started_at: "9/22/2022",
        deadline: "6/22/2023",
    },
    {
        project_id: 26,
        partner_image: "/images/logos/google.svg",
        partner_name: "ایسر",
        project_name: "وب‌دِو",
        project_desc:
            "یک سیستم هوش مصنوعی که می‌تواند فرمان‌های صوتی را تشخیص دهد و پاسخ دهد",
        tags: ["امنیت سایبری", "مدیریت سیستم", "رایانش ابری"],
        collaborators: [
            { name: "هارپر کولو", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 33,
        started_at: "6/22/2022",
        deadline: "5/22/2023",
    },
    {
        project_id: 27,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "مایکروسافت",
        project_name: "کلودی",
        project_desc:
            "ابزاری برای ساخت و میزبانی وب‌سایت‌های شخصی",
        tags: ["پژوهش فناوری اطلاعات", "واقعیت مجازی"],
        collaborators: [
            { name: "الکا رویس", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 62,
        started_at: "7/16/2022",
        deadline: "12/16/2022",
    },
    {
        project_id: 28,
        partner_image: "/images/logos/google.svg",
        partner_name: "اچ‌پی",
        project_name: "وی‌آر‌وای",
        project_desc:
            "یک سرویس رایانش ابری که ذخیره‌سازی، پردازش و منابع شبکه را ارائه می‌دهد",
        tags: ["یادگیری ماشین", "واقعیت مجازی", "اتوماسیون"],
        collaborators: [
            { name: "لیزبث شتفورد", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 15,
        started_at: "10/1/2022",
        deadline: "12/1/2022",
    },
    {
        project_id: 29,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "لاجیتک",
        project_name: "آی‌اوتایز",
        project_desc:
            "یک اپ واقعیت مجازی که به شما اجازه می‌دهد محیط‌های تعاملی خلق و کاوش کنید",
        tags: ["واقعیت مجازی"],
        collaborators: [
            { name: "دوری کوپیش", image: "/images/avatar/avatar-4.jpg" },
            { name: "Reza", image: undefined },
            { name: "لئونتین لنگمید", image: "/images/avatar/avatar-16.jpg" },
            { name: "فریکا گلادر", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 44,
        started_at: "6/4/2022",
        deadline: "5/4/2023",
    },
    {
        project_id: 30,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "مایکروسافت",
        project_name: "زیست‌فناوری",
        project_desc: "دستگاهی که هر شیئی را به اینترنت اشیا متصل می‌کند",
        tags: [
            "مشاوره فناوری اطلاعات",
            "رایانش ابری",
            "حاکمیت فناوری اطلاعات و استراتژی فناوری اطلاعات",
        ],
        collaborators: [
            { name: "Amir", image: undefined },
            { name: "کارلیک بورتومیو", image: "/images/avatar/avatar-14.jpg" },
            { name: "کوریس کومینگز", image: "/images/avatar/avatar-8.jpg" },
            { name: "دورا کیتمَن", image: "/images/avatar/avatar-14.jpg" },
            { name: "فاوستینا مک‌دوگال", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 77,
        started_at: "10/3/2022",
        deadline: "11/3/2022",
    },
    {
        project_id: 31,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "هواوی",
        project_name: "گیم‌آن",
        project_desc:
            "پروژه زیست‌فناوری که از موجودات زنده یا اجزای آن‌ها برای اهداف مختلف استفاده می‌کند",
        tags: ["طراحی رابط کاربری", "طراحی تجربه کاربری", "آموزش فناوری اطلاعات"],
        collaborators: [
            { name: "Heydari", image: undefined },
            { name: "الروی والینگر", image: "/images/avatar/avatar-9.jpg" },
            { name: "Fadaei", image: undefined },
        ],
        progress: 86,
        started_at: "1/7/2023",
        deadline: "7/7/2023",
    },
    {
        project_id: 32,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "اپل",
        project_name: "ادوتک",
        project_desc:
            "استودیوی تولید بازی که به توسعه و انتشار بازی‌های ویدیویی اختصاص دارد",
        tags: ["واقعیت افزوده"],
        collaborators: [
            { name: "Aghaei", image: undefined },
            { name: "حسین ایکهف", image: "/images/avatar/avatar-15.jpg" },
            { name: "آریکا مک‌کیتینگ", image: "/images/avatar/avatar-16.jpg" },
            { name: "ارین گالستورپ", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 10,
        started_at: "9/3/2022",
        deadline: "9/3/2023",
    },
    {
        project_id: 33,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "سامسونگ",
        project_name: "فین‌تک",
        project_desc:
            "یک پروژه فناوری آموزشی که یادگیری و آموزش را بهبود می‌بخشد",
        tags: ["بازی‌سازی", "اینترنت اشیا", "توسعه اپلیکیشن موبایل"],
        collaborators: [{ name: "Ali", image: undefined }],
        progress: 9,
        started_at: "5/14/2022",
        deadline: "7/14/2022",
    },
    {
        project_id: 34,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "سونی",
        project_name: "سلامت‌آی‌تی",
        project_desc:
            "پروژه فناوری مالی که راه‌حل‌های مبتکرانه‌ای برای بانکداری و امور مالی ارائه می‌دهد",
        tags: [
            "طراحی رابط کاربری",
            "بازاریابی دیجیتال",
            "مدیریت سیستم",
        ],
        collaborators: [
            { name: "دزموند بِوریج", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 71,
        started_at: "7/19/2022",
        deadline: "2/19/2023",
    },
    {
        project_id: 35,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "ایسر",
        project_name: "آی‌تی سبز",
        project_desc:
            "پروژه فناوری اطلاعات سلامت که بهبود ارائه و نتایج درمانی را دنبال می‌کند",
        tags: ["آموزش فناوری اطلاعات", "مشاوره فناوری اطلاعات"],
        collaborators: [
            { name: "اسپِنس بلک‌هام", image: "/images/avatar/avatar-10.jpg" },
            { name: "ویلو استرینگ‌فلو", image: "/images/avatar/avatar-16.jpg" },
            { name: "کندیس آلخاندرو", image: "/images/avatar/avatar-6.jpg" },
            { name: "Mosa", image: undefined },
            { name: "فلوری تانته", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 8,
        started_at: "8/4/2022",
        deadline: "8/4/2023",
    },
    {
        project_id: 36,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "سونی",
        project_name: "شبکه اجتماعی",
        project_desc:
            "یک پروژه ارز دیجیتال که از فناوری بلاک‌چین برای تراکنش‌های امن استفاده می‌کند",
        tags: ["توسعه اپلیکیشن موبایل", "ممیزی فناوری اطلاعات", "مدیریت سیستم"],
        collaborators: [
            { name: "Arri Matysik", image: undefined },
            { name: "Marinna Krelle", image: undefined },
            { name: "خوزه ایرنیس", image: "/images/avatar/avatar-18.jpg" },
            { name: "Hastie Narracott", image: undefined },
            { name: "ارما استرزاکر", image: "/images/avatar/avatar-6.jpg" },
        ],
        progress: 65,
        started_at: "5/13/2022",
        deadline: "1/13/2023",
    },
    {
        project_id: 37,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "سونی",
        project_name: "ای‌کام",
        project_desc:
            "پروژه فناوری محیط زیستی که ترویج پایداری و کاهش تاثیرات زیست‌محیطی را دنبال می‌کند",
        tags: ["تجارت الکترونیک"],
        collaborators: [
            { name: "نرون فولدز", image: "/images/avatar/avatar-16.jpg" },
            { name: "Kinny Terren", image: undefined },
            { name: "Montague Karlsen", image: undefined },
        ],
        progress: 34,
        started_at: "7/17/2022",
        deadline: "5/17/2023",
    },
    {
        project_id: 38,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "ایسوس",
        project_name: "مدیا لب",
        project_desc:
            "یک پروژه شبکه اجتماعی که افراد و جوامع را به هم متصل می‌کند",
        tags: ["رسانه اجتماعی", "مشاوره فناوری اطلاعات"],
        collaborators: [
            { name: "زاریا اسکولی", image: "/images/avatar/avatar-16.jpg" },
            { name: "مادلینا کاوستون", image: "/images/avatar/avatar-6.jpg" },
            { name: "Orlan Berrey", image: undefined },
        ],
        progress: 48,
        started_at: "1/22/2023",
        deadline: "10/22/2023",
    },
    {
        project_id: 39,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "سونی",
        project_name: "کدکس",
        project_desc:
            "یک پروژه تجارت الکترونیکی که محصولات یا خدمات را به صورت آنلاین به فروش می‌رساند",
        tags: ["اینترنت اشیا", "بلاک‌چین", "مشاوره فناوری اطلاعات"],
        collaborators: [
            { name: "استا آلاردایس", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 80,
        started_at: "12/19/2022",
        deadline: "11/19/2023",
    },
    {
        project_id: 40,
        partner_image: "/images/logos/google.svg",
        partner_name: "ریزر",
        project_name: "دیتا ویز",
        project_desc:
            "یک پروژه تولید رسانه که محتوای دیجیتال تولید و توزیع می‌کند",
        tags: ["پژوهش فناوری اطلاعات"],
        collaborators: [
            { name: "گوردان گرلیه", image: "/images/avatar/avatar-11.jpg" },
            { name: "هدویگ جریت", image: "/images/avatar/avatar-10.jpg" },
            { name: "Meggie Bernardt", image: undefined },
            { name: "Nara Dowsing", image: undefined },
        ],
        progress: 55,
        started_at: "11/1/2022",
        deadline: "4/1/2023",
    },
    {
        project_id: 41,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "ال‌جی",
        project_name: "خانه هوشمند",
        project_desc: "یک پلتفرم برای کدنویسی و رفع اشکال مشارکتی",
        tags: ["طراحی گرافیک"],
        collaborators: [
            { name: "ماتیاس اوکه", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 8,
        started_at: "1/22/2023",
        deadline: "6/22/2023",
    },
    {
        project_id: 42,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سونی",
        project_name: "امنیت سایبری",
        project_desc:
            "ابزاری برای ایجاد مصورسازی و داشبوردهای تعاملی داده",
        tags: ["بازی‌سازی", "توسعه وب", "رباتیک"],
        collaborators: [
            { name: "Pegeen Brear", image: undefined },
            { name: "برندن کابراس", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 80,
        started_at: "4/2/2023",
        deadline: "3/2/2024",
    },
    {
        project_id: 43,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "لنوو",
        project_name: "چت‌بات",
        project_desc:
            "یک سیستم برای کنترل و پایش دستگاه‌های هوشمند خانه شما",
        tags: ["امنیت سایبری"],
        collaborators: [
            { name: "جارت ریوَنس", image: "/images/avatar/avatar-1.jpg" },
            { name: "Archy Wahlberg", image: undefined },
            { name: "Freda Spat", image: undefined },
        ],
        progress: 54,
        started_at: "4/27/2023",
        deadline: "6/27/2023",
    },
    {
        project_id: 44,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "هواوی",
        project_name: "ایر",
        project_desc:
            "یک سیستم برای کنترل و پایش دستگاه‌های هوشمند خانه شما",
        tags: ["طراحی رابط کاربری"],
        collaborators: [
            { name: "پاتین گادسپید", image: "/images/avatar/avatar-14.jpg" },
            { name: "Howie Cable", image: undefined },
            { name: "Adler Keaveny", image: undefined },
            { name: "سوفی فریسل", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 55,
        started_at: "1/29/2023",
        deadline: "7/29/2023",
    },
    {
        project_id: 45,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "سامسونگ",
        project_name: "توسعه وب",
        project_desc: "یک چت‌بات که می‌تواند به سوالات پاسخ دهد و کمک ارائه دهد",
        tags: ["طراحی تجربه کاربری"],
        collaborators: [
            { name: "سیبیلا ودرآپ", image: "/images/avatar/avatar-4.jpg" },
            { name: "ایزیدورو سوبرت", image: "/images/avatar/avatar-11.jpg" },
            { name: "کری بلنکینگ", image: "/images/avatar/avatar-1.jpg" },
            { name: "ندی جورژو", image: "/images/avatar/avatar-7.jpg" },
            { name: "پاسکوال دنرت", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 85,
        started_at: "5/20/2022",
        deadline: "4/20/2023",
    },
    {
        project_id: 46,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "نینتندو",
        project_name: "کلودی",
        project_desc:
            "یک سامانه هوش مصنوعی که توانایی شناسایی و پاسخ به فرمان‌های صوتی را دارد",
        tags: ["بازی‌سازی", "آموزش فناوری اطلاعات", "واقعیت مجازی"],
        collaborators: [
            { name: "کارسا فیتون", image: "/images/avatar/avatar-6.jpg" },
            { name: "مگنوم ون زون", image: "/images/avatar/avatar-9.jpg" },
            { name: "Lacy Rugiero", image: undefined },
            { name: "روبینتا شویسمیت", image: "/images/avatar/avatar-20.jpg" },
            { name: "Norby Stogill", image: undefined },
        ],
        progress: 48,
        started_at: "2/26/2023",
        deadline: "12/26/2023",
    },
    {
        project_id: 47,
        partner_image: "/images/logos/google.svg",
        partner_name: "اپل",
        project_name: "وی‌آرای",
        project_desc:
            "یک سایت‌ساز که به شما اجازه می‌دهد سایت‌های خود را ایجاد و میزبانی کنید",
        tags: ["واقعیت افزوده"],
        collaborators: [
            { name: "جایمه کاردوسو", image: "/images/avatar/avatar-9.jpg" },
            { name: "Alaster Totterdill", image: undefined },
            { name: "روزینا کرید", image: "/images/avatar/avatar-20.jpg" },
            { name: "Leela Gatchel", image: undefined },
        ],
        progress: 69,
        started_at: "8/7/2022",
        deadline: "10/7/2022",
    },
    {
        project_id: 48,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "سامسونگ",
        project_name: "آی‌اوتایز",
        project_desc:
            "یک سرویس رایانش ابری که منابع ذخیره‌سازی، محاسبات و شبکه را ارائه می‌دهد",
        tags: ["تجارت الکترونیک"],
        collaborators: [
            { name: "Fancie Cramond", image: undefined },
            { name: "Bride St. Leger", image: undefined },
            { name: "ابرا اینفانته", image: "/images/avatar/avatar-1.jpg" },
            { name: "گاتری موشت", image: "/images/avatar/avatar-2.jpg" },
            { name: "دیتا سیمو", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 46,
        started_at: "3/16/2023",
        deadline: "4/16/2023",
    },
    {
        project_id: 49,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "ریزر",
        project_name: "بایوتک",
        project_desc:
            "یک اپلیکیشن واقعیت مجازی که به شما امکان می‌دهد محیط‌های فراگیر ایجاد و کاوش کنید",
        tags: ["پژوهش فناوری اطلاعات"],
        collaborators: [
            { name: "کرت دافی", image: "/images/avatar/avatar-20.jpg" },
            { name: "Winston Caddell", image: undefined },
            { name: "Ebeneser Francesconi", image: undefined },
            { name: "ورن فورتی", image: "/images/avatar/avatar-8.jpg" },
            { name: "داگ پالمر", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 8,
        started_at: "11/5/2022",
        deadline: "7/5/2023",
    },
    {
        project_id: 50,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "اپل",
        project_name: "گیم آن",
        project_desc: "یک دستگاه که هر شیئی را به اینترنت اشیا متصل می‌کند",
        tags: ["طراحی تجربه کاربری"],
        collaborators: [
            { name: "Brenden Murphy", image: undefined },
            { name: "داریل دودنی", image: "/images/avatar/avatar-5.jpg" },
            { name: "Pinchas Jeratt", image: undefined },
            { name: "آلین داین", image: "/images/avatar/avatar-9.jpg" },
            { name: "Jenifer Gregr", image: undefined },
        ],
        progress: 56,
        started_at: "1/31/2023",
        deadline: "5/31/2023",
    },
    {
        project_id: 51,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سامسونگ",
        project_name: "ادوتک",
        project_desc:
            "یک پروژه زیست‌فناوری که از موجودات زنده یا اجزای آنها برای کاربردهای مختلف بهره می‌گیرد",
        tags: ["رباتیک", "رایانش ابری"],
        collaborators: [
            { name: "Brandon Manterfield", image: undefined },
            { name: "Erena Dinning", image: undefined },
        ],
        progress: 35,
        started_at: "5/15/2022",
        deadline: "5/15/2023",
    },
    {
        project_id: 52,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "سامسونگ",
        project_name: "فین‌تک",
        project_desc:
            "یک استودیو توسعه بازی که بازی‌های ویدیویی خلق و منتشر می‌کند",
        tags: ["بلاک‌چین"],
        collaborators: [
            { name: "Finlay Popham", image: undefined },
            { name: "Dottie Pannaman", image: undefined },
            { name: "وارد ایوانیلوف", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 74,
        started_at: "6/18/2022",
        deadline: "9/18/2022",
    },
    {
        project_id: 53,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "ریزر",
        project_name: "سلامت‌آی‌تی",
        project_desc:
            "یک پروژه فناوری آموزشی که یادگیری و آموزش را بهبود می‌بخشد",
        tags: ["مدیریت پایگاه داده"],
        collaborators: [
            { name: "فاونیا مک‌کدی", image: "/images/avatar/avatar-18.jpg" },
            { name: "ریکاردو بلیک", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 69,
        started_at: "8/12/2022",
        deadline: "10/12/2022",
    },
    {
        project_id: 54,
        partner_image: "/images/logos/google.svg",
        partner_name: "اچ‌پی",
        project_name: "آی‌تی سبز",
        project_desc:
            "یک پروژه فناوری مالی که راه‌حل‌های نوآورانه‌ای برای بانکداری و امور مالی ارائه می‌دهد",
        tags: ["پژوهش فناوری اطلاعات", "رباتیک", "توسعه اپلیکیشن موبایل"],
        collaborators: [
            { name: "سیماس گیلستین", image: "/images/avatar/avatar-14.jpg" },
            { name: "مورگان اسکریپس", image: "/images/avatar/avatar-19.jpg" },
            { name: "گارالد کاراهر", image: "/images/avatar/avatar-6.jpg" },
            { name: "آری جنی", image: "/images/avatar/avatar-4.jpg" },
        ],
        progress: 76,
        started_at: "12/24/2022",
        deadline: "10/24/2023",
    },
    {
        project_id: 55,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "مایکروسافت",
        project_name: "شبکه اجتماعی",
        project_desc:
            "یک پروژه فناوری اطلاعات سلامت که بهبود ارائه و نتایج درمانی را دنبال می‌کند",
        tags: ["مهندسی نرم‌افزار", "اتوماسیون"],
        collaborators: [
            { name: "کریستین آتی", image: "/images/avatar/avatar-16.jpg" },
            { name: "Chariot Blanque", image: undefined },
        ],
        progress: 9,
        started_at: "6/28/2022",
        deadline: "8/28/2022",
    },
    {
        project_id: 56,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "ال‌جی",
        project_name: "ای‌کام",
        project_desc:
            "یک پروژه ارز دیجیتال که از فناوری بلاک‌چین برای تراکنش‌های امن استفاده می‌کند",
        tags: ["رباتیک", "طراحی گرافیک"],
        collaborators: [{ name: "Jolyn Osichev", image: undefined }],
        progress: 19,
        started_at: "12/9/2022",
        deadline: "3/9/2023",
    },
    {
        project_id: 57,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سونی",
        project_name: "مدیا لب",
        project_desc:
            "پروژه فناوری محیط زیستی که ترویج پایداری و کاهش تاثیرات زیست‌محیطی را دنبال می‌کند",
        tags: ["اتوماسیون"],
        collaborators: [
            { name: "Myrilla Skene", image: undefined },
            { name: "کیرستنی تروتول", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 33,
        started_at: "7/29/2022",
        deadline: "9/29/2022",
    },
    {
        project_id: 58,
        partner_image: "/images/logos/google.svg",
        partner_name: "دل",
        project_name: "کدکس",
        project_desc:
            "یک پروژه شبکه اجتماعی که افراد و جوامع را به هم متصل می‌کند",
        tags: ["مشاوره فناوری اطلاعات", "طراحی گرافیک"],
        collaborators: [
            { name: "Rona Biggerdike", image: undefined },
            { name: "Carrie Leibold", image: undefined },
            { name: "ابرا فنگ", image: "/images/avatar/avatar-9.jpg" },
            { name: "شف دالییل", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 98,
        started_at: "4/14/2023",
        deadline: "10/14/2023",
    },
    {
        project_id: 59,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "اچ‌پی",
        project_name: "دیتاویز",
        project_desc:
            "یک پروژه تجارت الکترونیک که محصولات یا خدمات را به صورت آنلاین می‌فروشد",
        tags: ["طراحی رابط کاربری", "مهندسی نرم‌افزار", "واقعیت مجازی"],
        collaborators: [
            { name: "ایدی ترووِرت", image: "/images/avatar/avatar-7.jpg" },
            { name: "موینا لیمپرتز", image: "/images/avatar/avatar-20.jpg" },
            { name: "میشا کامیلتّی", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 29,
        started_at: "11/29/2022",
        deadline: "10/29/2023",
    },
    {
        project_id: 60,
        partner_image: "/images/logos/google.svg",
        partner_name: "سونی",
        project_name: "خانه هوشمند",
        project_desc:
            "یک پروژه تولید رسانه که محتواهای دیجیتال تولید و توزیع می‌کند",
        tags: ["مدیریت پایگاه داده", "بازی‌سازی"],
        collaborators: [
            { name: "یونیس فتکین", image: "/images/avatar/avatar-8.jpg" },
            { name: "جث جینس", image: "/images/avatar/avatar-16.jpg" },
            { name: "داربی رولز", image: "/images/avatar/avatar-17.jpg" },
            { name: "سالی اَدی", image: "/images/avatar/avatar-20.jpg" },
            { name: "اورلاندو الدریج", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 90,
        started_at: "2/25/2023",
        deadline: "5/25/2023",
    },
    {
        project_id: 61,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سامسونگ",
        project_name: "امنیت سایبری",
        project_desc: "یک پلتفرم برای برنامه‌نویسی و اشکال‌یابی مشارکتی",
        tags: ["مدیریت فناوری اطلاعات و راهبرد فناوری اطلاعات"],
        collaborators: [{ name: "Jania Beccles", image: undefined }],
        progress: 48,
        started_at: "10/1/2022",
        deadline: "9/1/2023",
    },
    {
        project_id: 62,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "اپل",
        project_name: "چت‌بات",
        project_desc:
            "ابزاری برای تولید داشبورد و مصورسازی تعاملی داده‌ها",
        tags: ["مشاوره فناوری اطلاعات", "یادگیری ماشین"],
        collaborators: [
            { name: "کری چالن", image: "/images/avatar/avatar-6.jpg" },
            { name: "Dee Stagg", image: undefined },
        ],
        progress: 47,
        started_at: "7/16/2022",
        deadline: "11/16/2022",
    },
    {
        project_id: 63,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سامسونگ",
        project_name: "ایر",
        project_desc:
            "سیستم برای کنترل و پایش دستگاه‌های هوشمند خانه",
        tags: ["یادگیری ماشین"],
        collaborators: [
            { name: "سسیا وارنه", image: "/images/avatar/avatar-6.jpg" },
            { name: "رابرت هینو", image: "/images/avatar/avatar-10.jpg" },
            { name: "کلمانس پرسلُو", image: "/images/avatar/avatar-5.jpg" },
            { name: "Kimbell Vinick", image: undefined },
        ],
        progress: 41,
        started_at: "7/23/2022",
        deadline: "9/23/2022",
    },
    {
        project_id: 64,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سونی",
        project_name: "وب‌دِو",
        project_desc:
            "سیستم کنترل و پایش دستگاه‌های هوشمند خانه",
        tags: ["مشاوره فناوری اطلاعات", "واقعیت مجازی", "رسانه‌های اجتماعی"],
        collaborators: [
            { name: "Ricard Goldsmith", image: undefined },
            { name: "جرَلی بارتوزک", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 87,
        started_at: "12/11/2022",
        deadline: "9/11/2023",
    },
    {
        project_id: 65,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "سامسونگ",
        project_name: "کلودی",
        project_desc: "چت‌بوتی که به سوالات پاسخ داده و کمک می‌کند",
        tags: ["یادگیری ماشین", "مدیریت پایگاه داده", "طراحی گرافیک"],
        collaborators: [
            { name: "جنی مک‌درمید", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 20,
        started_at: "7/7/2022",
        deadline: "3/7/2023",
    },
    {
        project_id: 66,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "هوآوی",
        project_name: "وی‌آرای",
        project_desc:
            "سیستم هوش مصنوعی که دستورات صوتی را تشخیص داده و واکنش نشان می‌دهد",
        tags: ["آموزش فناوری اطلاعات", "هوش مصنوعی"],
        collaborators: [
            { name: "Delmer Rubens", image: undefined },
            { name: "Armando Melbert", image: undefined },
        ],
        progress: 19,
        started_at: "6/12/2022",
        deadline: "3/12/2023",
    },
    {
        project_id: 67,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "اپل",
        project_name: "اینترنت اشیا",
        project_desc:
            "سایت‌سازی برای ساخت و میزبانی سایت‌های اختصاصی شما",
        tags: ["رباتیک", "بازاریابی دیجیتال", "طراحی تجربه کاربری"],
        collaborators: [
            { name: "Monti Benning", image: undefined },
            { name: "Lane Nudds", image: undefined },
            { name: "سابینا آرمیت", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 45,
        started_at: "11/17/2022",
        deadline: "10/17/2023",
    },
    {
        project_id: 68,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سامسونگ",
        project_name: "بیوتِک",
        project_desc:
            "سرویس رایانش ابری که ذخیره‌سازی، پردازش و شبکه را ارائه می‌دهد",
        tags: ["امنیت سایبری"],
        collaborators: [
            { name: "Rutger Dudeney", image: undefined },
            { name: "گرادی مک‌ترسترام", image: "/images/avatar/avatar-14.jpg" },
            { name: "شینا بایرد", image: "/images/avatar/avatar-7.jpg" },
            { name: "Arabel Vasenin", image: undefined },
        ],
        progress: 28,
        started_at: "7/21/2022",
        deadline: "10/21/2022",
    },
    {
        project_id: 69,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "ال‌جی",
        project_name: "گیم‌آن",
        project_desc:
            "اپلیکیشن واقعیت مجازی برای کشف و ساخت محیط‌های فراگیر",
        tags: ["داده‌کاوی"],
        collaborators: [
            { name: "کیِل کاتن", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 48,
        started_at: "11/18/2022",
        deadline: "9/18/2023",
    },
    {
        project_id: 70,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "دل",
        project_name: "ادوتک",
        project_desc: "دستگاهی که هر جسمی را به اینترنت اشیا متصل می‌کند",
        tags: ["پشتیبانی فنی", "یادگیری ماشین", "مدیریت سیستم"],
        collaborators: [
            { name: "تری دوریتی", image: "/images/avatar/avatar-12.jpg" },
            { name: "جود نکروز", image: "/images/avatar/avatar-12.jpg" },
            { name: "Lorilyn Dufaur", image: undefined },
            { name: "کلری پینچین", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 34,
        started_at: "2/1/2023",
        deadline: "7/1/2023",
    },
    {
        project_id: 71,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "ایسوس",
        project_name: "فین‌تک",
        project_desc:
            "پروژه زیست‌فن‌آوری که از موجودات زنده یا اجزای آن‌ها برای اهداف مختلف استفاده می‌کند",
        tags: ["پشتیبانی فنی"],
        collaborators: [
            { name: "ملینا گاتنبی", image: "/images/avatar/avatar-8.jpg" },
            { name: "لیولن تیثاکوت", image: "/images/avatar/avatar-11.jpg" },
            { name: "تمارا دوبری", image: "/images/avatar/avatar-2.jpg" },
            { name: "روزن لثربارو", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 29,
        started_at: "2/26/2023",
        deadline: "2/26/2024",
    },
    {
        project_id: 72,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "لنوو",
        project_name: "سلامت‌آی‌تی",
        project_desc:
            "استودیوی بازی‌سازی که به تولید و نشر بازی‌های رایانه‌ای می‌پردازد",
        tags: ["رسانه اجتماعی", "امنیت سایبری", "مهندسی نرم‌افزار"],
        collaborators: [
            { name: "کن چیز", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 59,
        started_at: "1/7/2023",
        deadline: "7/7/2023",
    },
    {
        project_id: 73,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "ایسر",
        project_name: "گرین‌ آی‌تی",
        project_desc:
            "پروژه فناوری آموزشی برای ارتقای یادگیری و تدریس",
        tags: ["طراحی رابط کاربری"],
        collaborators: [
            { name: "مرسی راشتون", image: "/images/avatar/avatar-16.jpg" },
            { name: "تارا ترولی", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 60,
        started_at: "8/30/2022",
        deadline: "6/30/2023",
    },
    {
        project_id: 74,
        partner_image: "/images/logos/google.svg",
        partner_name: "سامسونگ",
        project_name: "شبکه‌اجتماعی",
        project_desc:
            "پروژه فناوری مالی با راهکارهای نوآورانه برای بانکداری و امور مالی",
        tags: ["واقعیت مجازی", "مدیریت سیستم", "بازی‌سازی"],
        collaborators: [
            { name: "آردیث نات", image: "/images/avatar/avatar-12.jpg" },
            { name: "لنگستون بَتیست", image: "/images/avatar/avatar-15.jpg" },
            { name: "بابی ماتیوزی", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 50,
        started_at: "12/15/2022",
        deadline: "9/15/2023",
    },
    {
        project_id: 75,
        partner_image: "/images/logos/google.svg",
        partner_name: "نینتندو",
        project_name: "ای‌کام",
        project_desc:
            "یک پروژه فناوری اطلاعات سلامت برای بهبود ارائه و نتایج خدمات درمانی",
        tags: ["ممیزی فناوری اطلاعات", "مدیریت فناوری اطلاعات و راهبرد فناوری اطلاعات"],
        collaborators: [
            { name: "بلیسه گاواگان", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 71,
        started_at: "11/23/2022",
        deadline: "6/23/2023",
    },
    {
        project_id: 76,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سونی",
        project_name: "مدیا لب",
        project_desc:
            "پروژه رمزارز که داده‌ها را با فناوری بلاک‌چین امن انتقال می‌دهد",
        tags: ["رایانش ابری"],
        collaborators: [
            { name: "فِیث ماسه", image: "/images/avatar/avatar-4.jpg" },
            { name: "Jemmie Drieu", image: undefined },
            { name: "رژین مک‌گیف", image: "/images/avatar/avatar-2.jpg" },
        ],
        progress: 93,
        started_at: "5/17/2022",
        deadline: "9/17/2022",
    },
    {
        project_id: 77,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سونی",
        project_name: "کدکس",
        project_desc:
            "پروژه فناوری محیط زیستی که ترویج پایداری و کاهش تاثیرات زیست‌محیطی را دنبال می‌کند",
        tags: ["مشاوره فناوری اطلاعات", "امنیت سایبری"],
        collaborators: [
            { name: "روثان گریبرت", image: "/images/avatar/avatar-18.jpg" },
            { name: "بوگی آلبین", image: "/images/avatar/avatar-12.jpg" },
            { name: "ستانتون گورنال", image: "/images/avatar/avatar-20.jpg" },
            { name: "Trudie Bambery", image: undefined },
            { name: "گیبی پیتولی", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 53,
        started_at: "3/6/2023",
        deadline: "8/6/2023",
    },
    {
        project_id: 78,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "نینتندو",
        project_name: "دیتاویز",
        project_desc:
            "یک پروژه شبکه اجتماعی که افراد و جوامع را به هم متصل می‌کند",
        tags: ["مدیریت پایگاه داده", "واقعیت مجازی"],
        collaborators: [
            { name: "کلهون ریکرد", image: "/images/avatar/avatar-18.jpg" },
            { name: "ایزوبل نلیس", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 77,
        started_at: "7/6/2022",
        deadline: "9/6/2022",
    },
    {
        project_id: 79,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سونی",
        project_name: "خانه هوشمند",
        project_desc:
            "یک پروژه تجارت الکترونیک که محصولات یا خدمات را به صورت آنلاین می‌فروشد",
        tags: ["طراحی تجربه کاربری"],
        collaborators: [{ name: "Augustine Pockey", image: undefined }],
        progress: 95,
        started_at: "4/14/2023",
        deadline: "4/14/2024",
    },
    {
        project_id: 80,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "ریزر",
        project_name: "امنیت سایبری",
        project_desc:
            "پروژه تولید رسانه و تولید و توزیع محتوای دیجیتال",
        tags: ["طراحی تجربه کاربری", "توسعه وب", "بازاریابی دیجیتال"],
        collaborators: [
            { name: "مایلز کاپر", image: "/images/avatar/avatar-14.jpg" },
            { name: "Abagael Findlay", image: undefined },
            { name: "کالی اسپرینگِیت", image: "/images/avatar/avatar-15.jpg" },
            { name: "هِرتا بارو", image: "/images/avatar/avatar-12.jpg" },
            { name: "Sergei Housen", image: undefined },
        ],
        progress: 2,
        started_at: "5/1/2023",
        deadline: "5/1/2024",
    },
    {
        project_id: 81,
        partner_image: "/images/logos/google.svg",
        partner_name: "ایسر",
        project_name: "چت‌بات",
        project_desc: "پلتفرمی برای برنامه نویسی مشارکتی و رفع خطا",
        tags: ["بازاریابی دیجیتال", "رباتیک", "آموزش فناوری اطلاعات"],
        collaborators: [
            { name: "وندی رودیمَن", image: "/images/avatar/avatar-20.jpg" },
            { name: "Ruthann Todeo", image: undefined },
            { name: "دالیس ولاسنکو", image: "/images/avatar/avatar-13.jpg" },
            { name: "آروین پن‌هالرِک", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 37,
        started_at: "2/13/2023",
        deadline: "9/13/2023",
    },
    {
        project_id: 82,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "سونی",
        project_name: "ایر",
        project_desc:
            "ابزاری برای مصورسازی داده و داشبورد تعاملی",
        tags: ["یادگیری ماشین", "تجارت الکترونیک"],
        collaborators: [{ name: "Melantha Fayers", image: undefined }],
        progress: 41,
        started_at: "11/16/2022",
        deadline: "8/16/2023",
    },
    {
        project_id: 83,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "ایسر",
        project_name: "وب‌دِو",
        project_desc:
            "سیستم کنترل و پایش دستگاه‌های هوشمند خانه",
        tags: ["بلاک‌چین"],
        collaborators: [
            { name: "داماریس ویدراپ", image: "/images/avatar/avatar-19.jpg" },
            { name: "مرا لیدکر", image: "/images/avatar/avatar-13.jpg" },
        ],
        progress: 31,
        started_at: "6/2/2022",
        deadline: "12/2/2022",
    },
    {
        project_id: 84,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "ایسر",
        project_name: "کلودی",
        project_desc:
            "سیستم کنترل و پایش دستگاه‌های هوشمند خانه",
        tags: ["رباتیک", "مدیریت سیستم"],
        collaborators: [
            { name: "گوتفرید هِدینگ", image: "/images/avatar/avatar-3.jpg" },
            { name: "Gaylor Nezey", image: undefined },
            { name: "کثی پوسِلت", image: "/images/avatar/avatar-16.jpg" },
            { name: "هِنریتا لُور", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 50,
        started_at: "12/2/2022",
        deadline: "7/2/2023",
    },
    {
        project_id: 85,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "ایسر",
        project_name: "وی‌آرای",
        project_desc: "چت‌بوتی که به سوالات پاسخ داده و کمک می‌کند",
        tags: ["رباتیک", "پشتیبانی فنی", "مدیریت فناوری اطلاعات و راهبرد فناوری اطلاعات"],
        collaborators: [
            { name: "گرالد فرانسن", image: "/images/avatar/avatar-4.jpg" },
            { name: "سیندی ستونل", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 12,
        started_at: "3/15/2023",
        deadline: "2/15/2024",
    },
    {
        project_id: 86,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "سامسونگ",
        project_name: "اینترنت اشیا",
        project_desc:
            "سیستم هوش مصنوعی که دستورات صوتی را تشخیص داده و پاسخ می‌دهد",
        tags: [
            "طراحی رابط کاربری",
            "مهندسی نرم‌افزار",
            "هوش مصنوعی",
        ],
        collaborators: [
            { name: "جنوویو بارتولین", image: "/images/avatar/avatar-4.jpg" },
            { name: "کلارک اِدکینز", image: "/images/avatar/avatar-13.jpg" },
            { name: "الوینیا وایلس", image: "/images/avatar/avatar-17.jpg" },
            { name: "بابی بلکستن", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 83,
        started_at: "4/26/2023",
        deadline: "8/26/2023",
    },
    {
        project_id: 87,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "هوآوی",
        project_name: "بیوتک",
        project_desc:
            "ابزار سایت‌سازی برای ساخت و میزبانی سایت‌های شما",
        tags: ["هوش مصنوعی"],
        collaborators: [
            { name: "جویای دلوُنا", image: "/images/avatar/avatar-17.jpg" },
            { name: "Amaleta Bonwick", image: undefined },
            { name: "رافائل مارویک", image: "/images/avatar/avatar-7.jpg" },
        ],
        progress: 13,
        started_at: "5/1/2023",
        deadline: "3/1/2024",
    },
    {
        project_id: 88,
        partner_image: "/images/logos/google.svg",
        partner_name: "اپل",
        project_name: "گیم‌آن",
        project_desc:
            "یک سرویس رایانش ابری برای ذخیره‌سازی، پردازش و شبکه",
        tags: ["طراحی رابط کاربری", "مدیریت پایگاه داده"],
        collaborators: [
            { name: "هدی فیلیپسون", image: "/images/avatar/avatar-15.jpg" },
            { name: "Muffin Newsome", image: undefined },
            { name: "آنتونیتا مک‌کروری", image: "/images/avatar/avatar-15.jpg" },
            { name: "Berta Gomery", image: undefined },
        ],
        progress: 9,
        started_at: "7/4/2022",
        deadline: "2/4/2023",
    },
    {
        project_id: 89,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "ریزر",
        project_name: "ادوتک",
        project_desc:
            "اپلیکیشن واقعیت مجازی برای کشف و ساخت محیط‌های فراگیر",
        tags: ["پشتیبانی فنی"],
        collaborators: [
            { name: "توبی استگرز", image: "/images/avatar/avatar-13.jpg" },
            { name: "جانه برادر", image: "/images/avatar/avatar-11.jpg" },
            { name: "Jillane Scott", image: undefined },
        ],
        progress: 27,
        started_at: "9/14/2022",
        deadline: "10/14/2022",
    },
    {
        project_id: 90,
        partner_image: "/images/logos/google.svg",
        partner_name: "نینتندو",
        project_name: "فین‌تک",
        project_desc: "دستگاهی که هر جسمی را به اینترنت اشیا متصل می‌کند",
        tags: ["مشاوره فناوری اطلاعات", "مهندسی نرم‌افزار"],
        collaborators: [
            { name: "اسمی کلاوی", image: "/images/avatar/avatar-7.jpg" },
            { name: "پتسی استانویکس", image: "/images/avatar/avatar-1.jpg" },
            { name: "ادی دابر", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 38,
        started_at: "5/21/2022",
        deadline: "8/21/2022",
    },
    {
        project_id: 91,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "اچ‌پی",
        project_name: "سلامت‌آی‌تی",
        project_desc:
            "پروژه زیست‌فناوری که از موجودات زنده برای اهداف گوناگون استفاده می‌کند",
        tags: ["مدیریت شبکه", "اینترنت اشیا"],
        collaborators: [
            { name: "کلبی اورلیچ", image: "/images/avatar/avatar-19.jpg" },
        ],
        progress: 66,
        started_at: "8/24/2022",
        deadline: "8/24/2023",
    },
    {
        project_id: 92,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "ال‌جی",
        project_name: "گرین‌ آی‌تی",
        project_desc:
            "استودیوی بازی‌سازی که تولید و نشر بازی‌های ویدیویی انجام می‌دهد",
        tags: ["اینترنت اشیا", "اتوماسیون"],
        collaborators: [
            { name: "کوردی آندراس", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 93,
        started_at: "7/28/2022",
        deadline: "9/28/2022",
    },
    {
        project_id: 93,
        partner_image: "/images/logos/google.svg",
        partner_name: "هوآوی",
        project_name: "شبکه‌اجتماعی",
        project_desc:
            "پروژه فناوری آموزشی برای ارتقا یادگیری و تدریس",
        tags: ["مدیریت پایگاه داده", "پشتیبانی فنی"],
        collaborators: [
            { name: "اوربان اُتلی", image: "/images/avatar/avatar-18.jpg" },
        ],
        progress: 96,
        started_at: "11/20/2022",
        deadline: "4/20/2023",
    },
    {
        project_id: 94,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "لنوو",
        project_name: "ای‌کام",
        project_desc:
            "پروژه فناوری مالی با راهکارهای مالی و بانکی نوین",
        tags: ["طراحی گرافیک", "رایانش ابری"],
        collaborators: [
            { name: "Sheri McGeachey", image: undefined },
            { name: "لکسی گادسدن", image: "/images/avatar/avatar-4.jpg" },
            { name: "Alleen Soar", image: undefined },
            { name: "کاریسا مک‌اسپیرون", image: "/images/avatar/avatar-2.jpg" },
            { name: "وودرو آیلز", image: "/images/avatar/avatar-7.jpg" },
        ],
        progress: 97,
        started_at: "6/18/2022",
        deadline: "2/18/2023",
    },
    {
        project_id: 95,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "دل",
        project_name: "مدیا لب",
        project_desc:
            "پروژه فناوری اطلاعات سلامت برای ارتقای خدمات درمانی",
        tags: ["ممیزی فناوری اطلاعات"],
        collaborators: [
            { name: "هَلی شولز", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 28,
        started_at: "3/9/2023",
        deadline: "2/9/2024",
    },
    {
        project_id: 96,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "دل",
        project_name: "کدکس",
        project_desc:
            "پروژه رمزارز که تعاملات را با استفاده از بلاک‌چین امن می‌کند",
        tags: ["توسعه اپلیکیشن موبایل"],
        collaborators: [
            { name: "گرائم واس", image: "/images/avatar/avatar-3.jpg" },
            { name: "سیوبان مک‌کیم", image: "/images/avatar/avatar-7.jpg" },
            { name: "فیلیدا میکلویچ", image: "/images/avatar/avatar-1.jpg" },
            { name: "نوربی اسکیبز", image: "/images/avatar/avatar-15.jpg" },
            { name: "Darrin Gallamore", image: undefined },
        ],
        progress: 9,
        started_at: "4/27/2023",
        deadline: "1/27/2024",
    },
    {
        project_id: 97,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "ایسوس",
        project_name: "دیتاویز",
        project_desc:
            "پروژه فناوری محیط زیستی برای توسعه پایدار و کاهش آثار منفی زیست‌محیطی",
        tags: ["امنیت سایبری", "مدیریت پایگاه داده", "رایانش ابری"],
        collaborators: [
            { name: "جسی هیون", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 89,
        started_at: "10/25/2022",
        deadline: "9/25/2023",
    },
    {
        project_id: 98,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "سونی",
        project_name: "خانه هوشمند",
        project_desc:
            "پروژه شبکه اجتماعی که افراد و انجمن‌ها را به هم مرتبط می‌کند",
        tags: ["مدیریت فناوری اطلاعات و راهبری فناوری اطلاعات", "مدیریت سیستم"],
        collaborators: [
            { name: "جولی دودک", image: "/images/avatar/avatar-5.jpg" },
            { name: "التیا جین‌دریسک", image: "/images/avatar/avatar-4.jpg" },
        ],
        progress: 79,
        started_at: "3/8/2023",
        deadline: "1/8/2024",
    },
    {
        project_id: 99,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "مایکروسافت",
        project_name: "امنیت سایبری",
        project_desc:
            "پروژه تجارت الکترونیک برای فروش آنلاین محصولات و خدمات",
        tags: ["مشاوره فناوری اطلاعات"],
        collaborators: [
            { name: "گالوین مایر", image: "/images/avatar/avatar-7.jpg" },
            { name: "رامونا فربروگه", image: "/images/avatar/avatar-11.jpg" },
            { name: "کوینلان رووِن", image: "/images/avatar/avatar-19.jpg" },
            { name: "Callie Clutten", image: undefined },
            { name: "Addi Tyhurst", image: undefined },
        ],
        progress: 53,
        started_at: "3/1/2023",
        deadline: "5/1/2023",
    },
    {
        project_id: 100,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "نینتندو",
        project_name: "چت‌بات",
        project_desc:
            "پروژه تولید رسانه برای تولید و انتشار محتوای دیجیتال",
        tags: ["توسعه وب", "طراحی رابط کاربری"],
        collaborators: [
            { name: "سیانا لارچر", image: "/images/avatar/avatar-3.jpg" },
            { name: "Silvester Helis", image: undefined },
        ],
        progress: 92,
        started_at: "1/16/2023",
        deadline: "7/16/2023",
    },
];
