export interface CryptoActivity {
  activity_id: number;
  activity_type: { key: string; title: string };
  activity_name: string;
  account_name: string;
  transaction_date: string;
  amount: number;
}

export const activityList: CryptoActivity[] = [
  {
    activity_id: 1,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "پنج‌شنبه، ۱۲ فروردین - 14:23",
    amount: -6.33,
  },
  {
    activity_id: 2,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۲۷ اردیبهشت - 09:15",
    amount: -3.97,
  },
  {
    activity_id: 3,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "جمعه، ۵ خرداد - 18:40",
    amount: 9.65,
  },
  {
    activity_id: 4,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۱۹ مرداد - 07:50",
    amount: -6.0,
  },
  {
    activity_id: 5,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۳ آبان - 12:10",
    amount: -4.32,
  },
  {
    activity_id: 6,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۲۱ دی - 16:35",
    amount: 3.44,
  },
  {
    activity_id: 7,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "پنج‌شنبه، ۱۰ خرداد - 11:05",
    amount: -2.68,
  },
  {
    activity_id: 8,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "سه‌شنبه، ۱۷ شهریور - 20:45",
    amount: 7.36,
  },
  {
    activity_id: 9,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۳۰ آبان - 08:20",
    amount: 4.23,
  },
  {
    activity_id: 10,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "دوشنبه، ۱۲ دی - 14:50",
    amount: -5.42,
  },
  {
    activity_id: 11,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "شنبه، ۲۴ خرداد - 09:30",
    amount: 5.89,
  },
  {
    activity_id: 12,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "چهارشنبه، ۱۰ اردیبهشت - 08:45",
    amount: 2.14,
  },
  {
    activity_id: 13,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "یکشنبه، ۲۴ خرداد - 14:20",
    amount: 7.85,
  },
  {
    activity_id: 14,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۱۵ مهر - 17:05",
    amount: 6.71,
  },
  {
    activity_id: 15,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۶ شهریور - 09:30",
    amount: 6.14,
  },
  {
    activity_id: 16,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "سه‌شنبه، ۱۹ دی - 11:15",
    amount: 1.81,
  },
  {
    activity_id: 17,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "پنج‌شنبه، ۲۷ خرداد - 16:50",
    amount: 1.28,
  },
  {
    activity_id: 18,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "شنبه، ۱۱ آبان - 13:05",
    amount: 5.97,
  },
  {
    activity_id: 19,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "یکشنبه، ۲۳ مهر - 10:40",
    amount: 8.42,
  },
  {
    activity_id: 20,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۵ اسفند - 07:55",
    amount: -6.37,
  },
  {
    activity_id: 21,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۱۴ آذر - 12:30",
    amount: 5.17,
  },
  {
    activity_id: 22,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۲۲ دی - 09:45",
    amount: 1.99,
  },
  {
    activity_id: 23,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "پنج‌شنبه، ۹ مرداد - 15:10",
    amount: 6.11,
  },
  {
    activity_id: 24,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "شنبه، ۳۱ شهریور - 18:25",
    amount: -6.17,
  },
  {
    activity_id: 25,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۱۲ مهر - 10:50",
    amount: 6.5,
  },
  {
    activity_id: 26,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "شنبه، ۱۰ اردیبهشت - 14:10",
    amount: 8.44,
  },
  {
    activity_id: 27,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۲۵ خرداد - 09:35",
    amount: -3.15,
  },
  {
    activity_id: 28,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۱۲ تیر - 17:50",
    amount: -8.46,
  },
  {
    activity_id: 29,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۳ مرداد - 12:25",
    amount: 8.28,
  },
  {
    activity_id: 30,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۲۵ شهریور - 08:45",
    amount: 4.14,
  },
  {
    activity_id: 31,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۳ مهر - 15:30",
    amount: 9.83,
  },
  {
    activity_id: 32,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "پنج‌شنبه، ۵ آبان - 10:15",
    amount: -3.06,
  },
  {
    activity_id: 33,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "شنبه، ۲۳ آذر - 16:40",
    amount: 2.61,
  },
  {
    activity_id: 34,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "یکشنبه، ۷ دی - 11:55",
    amount: 1.12,
  },
  {
    activity_id: 35,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "چهارشنبه، ۲۵ بهمن - 13:20",
    amount: 8.48,
  },
  {
    activity_id: 36,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "شنبه، ۱۵ فروردین - 11:20",
    amount: -7.54,
  },
  {
    activity_id: 37,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۲۰ اردیبهشت - 09:45",
    amount: 7.16,
  },
  {
    activity_id: 38,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "سه‌شنبه، ۱ خرداد - 14:10",
    amount: -2.79,
  },
  {
    activity_id: 39,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۲۷ مرداد - 16:35",
    amount: 6.26,
  },
  {
    activity_id: 40,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "دوشنبه، ۷ تیر - 12:50",
    amount: 4.24,
  },
  {
    activity_id: 41,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "پنج‌شنبه، ۱۴ شهریور - 10:15",
    amount: -2.26,
  },
  {
    activity_id: 42,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "شنبه، ۱ مهر - 15:40",
    amount: 3.88,
  },
  {
    activity_id: 43,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۲۲ آبان - 13:25",
    amount: -8.27,
  },
  {
    activity_id: 44,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "جمعه، ۸ مهر - 17:10",
    amount: 9.52,
  },
  {
    activity_id: 45,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "سه‌شنبه، ۳ شهریور - 09:55",
    amount: -3.79,
  },
  {
    activity_id: 46,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۲۷ شهریور - 11:45",
    amount: 5.39,
  },
  {
    activity_id: 47,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "شنبه، ۲۹ شهریور - 10:05",
    amount: 0.93,
  },
  {
    activity_id: 48,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۱۵ آبان - 14:30",
    amount: -5.54,
  },
  {
    activity_id: 49,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "یکشنبه، ۱۰ تیر - 08:50",
    amount: 0.84,
  },
  {
    activity_id: 50,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "دوشنبه، ۲۵ شهریور - 16:15",
    amount: -6.49,
  },
  {
    activity_id: 51,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۲۵ فروردین - 10:15",
    amount: -1.51,
  },
  {
    activity_id: 52,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "شنبه، ۱۵ خرداد - 14:50",
    amount: 9.73,
  },
  {
    activity_id: 53,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۳۰ خرداد - 12:35",
    amount: 9.55,
  },
  {
    activity_id: 54,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۱۸ تیر - 09:20",
    amount: 4.98,
  },
  {
    activity_id: 55,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۱۰ مرداد - 16:05",
    amount: -5.04,
  },
  {
    activity_id: 56,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "پنج‌شنبه، ۲۵ شهریور - 11:30",
    amount: -4.23,
  },
  {
    activity_id: 57,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۷ مهر - 15:40",
    amount: 9.49,
  },
  {
    activity_id: 58,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "یکشنبه، ۲۵ مهر - 10:55",
    amount: 4.33,
  },
  {
    activity_id: 59,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۱۴ آبان - 13:20",
    amount: -2.58,
  },
  {
    activity_id: 60,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۲۵ آذر - 09:45",
    amount: -0.5,
  },
  {
    activity_id: 61,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "دوشنبه، ۲۵ اردیبهشت - 11:50",
    amount: -8.97,
  },
  {
    activity_id: 62,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۱۵ خرداد - 14:20",
    amount: 3.93,
  },
  {
    activity_id: 63,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "سه‌شنبه، ۲۴ خرداد - 09:35",
    amount: 2.23,
  },
  {
    activity_id: 64,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "چهارشنبه، ۳ تیر - 16:10",
    amount: -3.79,
  },
  {
    activity_id: 65,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "بیمه",
    account_name: "لایت کوین",
    transaction_date: "پنج‌شنبه، ۱۵ مرداد - 12:25",
    amount: -2.92,
  },
  {
    activity_id: 66,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "شنبه، ۷ مرداد - 10:50",
    amount: 2.53,
  },
  {
    activity_id: 67,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "یکشنبه، ۲۴ تیر - 13:40",
    amount: 5.95,
  },
  {
    activity_id: 68,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۱۰ مرداد - 11:15",
    amount: 0.9,
  },
  {
    activity_id: 69,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "چهارشنبه، ۳۱ خرداد - 14:30",
    amount: -7.79,
  },
  {
    activity_id: 70,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "سه‌شنبه، ۲ تیر - 09:50",
    amount: -3.88,
  },
  {
    activity_id: 71,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "آلفردو الیوت",
    account_name: "بیت کوین",
    transaction_date: "سه‌شنبه، ۱ مرداد - 14:25",
    amount: 8.53,
  },
  {
    activity_id: 72,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۲۵ اردیبهشت - 09:50",
    amount: -5.97,
  },
  {
    activity_id: 73,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۱۰ خرداد - 11:15",
    amount: -8.47,
  },
  {
    activity_id: 74,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۲۵ تیر - 10:40",
    amount: 4.3,
  },
  {
    activity_id: 75,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "شنبه، ۵ مرداد - 15:30",
    amount: 9.83,
  },
  {
    activity_id: 76,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "پنج‌شنبه، ۱۵ مرداد - 12:10",
    amount: -2.31,
  },
  {
    activity_id: 77,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۱۲ خرداد - 13:45",
    amount: 6.32,
  },
  {
    activity_id: 78,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "یکشنبه، ۲۴ تیر - 10:50",
    amount: -2.17,
  },
  {
    activity_id: 79,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۱ مرداد - 11:25",
    amount: 2.39,
  },
  {
    activity_id: 80,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "جمعه، ۲۹ تیر - 09:50",
    amount: 4.41,
  },
  {
    activity_id: 81,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۴ مرداد - 14:10",
    amount: 8.06,
  },
  {
    activity_id: 82,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۱۳ خرداد - 10:30",
    amount: 1.56,
  },
  {
    activity_id: 83,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۲ مرداد - 12:20",
    amount: 3.95,
  },
  {
    activity_id: 84,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۱۸ تیر - 15:05",
    amount: -7.7,
  },
  {
    activity_id: 85,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "جمعه، ۲۱ تیر - 13:45",
    amount: 9.04,
  },
  {
    activity_id: 86,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "شنبه، ۳۰ تیر - 12:10",
    amount: 5.4,
  },
  {
    activity_id: 87,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "دوشنبه، ۲۰ خرداد - 11:25",
    amount: -1.86,
  },
  {
    activity_id: 88,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۲۴ خرداد - 14:50",
    amount: 5.1,
  },
  {
    activity_id: 89,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۱۱ خرداد - 10:40",
    amount: 6.71,
  },
  {
    activity_id: 90,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۳ تیر - 15:05",
    amount: 5.12,
  },
  {
    activity_id: 91,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "شنبه، ۶ مرداد - 09:35",
    amount: -0.4,
  },
  {
    activity_id: 92,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "بیت کوین",
    transaction_date: "سه‌شنبه، ۱۶ خرداد - 13:20",
    amount: 3.21,
  },
  {
    activity_id: 93,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "برق",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۲۵ خرداد - 11:50",
    amount: -5.77,
  },
  {
    activity_id: 94,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "بیمه",
    account_name: "اتریوم",
    transaction_date: "دوشنبه، ۱۲ تیر - 14:10",
    amount: 3.87,
  },
  {
    activity_id: 95,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "بیت کوین",
    transaction_date: "یکشنبه، ۹ تیر - 10:20",
    amount: -0.19,
  },
  {
    activity_id: 96,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "برق",
    account_name: "لایت کوین",
    transaction_date: "جمعه، ۲۹ خرداد - 12:00",
    amount: -9.79,
  },
  {
    activity_id: 97,
    activity_type: { key: "property-coverage", title: "پوشش اموال" },
    activity_name: "آلفردو الیوت",
    account_name: "لایت کوین",
    transaction_date: "سه‌شنبه، ۲۴ خرداد - 14:25",
    amount: -9.54,
  },
  {
    activity_id: 98,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "آلفردو الیوت",
    account_name: "اتریوم",
    transaction_date: "چهارشنبه، ۴ تیر - 11:15",
    amount: -0.49,
  },
  {
    activity_id: 99,
    activity_type: { key: "personal", title: "شخصی" },
    activity_name: "کانر گوزمن",
    account_name: "اتریوم",
    transaction_date: "سه‌شنبه، ۳ تیر - 13:40",
    amount: -7.83,
  },
  {
    activity_id: 100,
    activity_type: { key: "utility-payment", title: "پرداخت قبض" },
    activity_name: "کانر گوزمن",
    account_name: "لایت کوین",
    transaction_date: "چهارشنبه، ۱۱ تیر - 12:30",
    amount: -8.22,
  },
];
