export type Status = "in-progress" | "done" | "pending";

export interface Project {
  project_id: string;
  partner_image: string;
  partner_name: string;
  project_name: string;
  project_desc: string;
  tags: string[];
  collaborators: string[];
  progress: number;
  status: Status;
  started_at: number;
  deadline: number;
}

export interface Collaborator {
  uid: string;
  name: string;
  avatar?: string;
}

export interface Tag {
  value: string;
  label: string;
}

export const projectsList: Project[] = [
  {
    project_id: "1",
    partner_image: "/images/logos/google.svg",
    partner_name: "سامسونگ",
    project_name: "کدکس",
    project_desc: "یک پلتفرم برای برنامه‌نویسی و اشکال‌زدایی مشارکتی",
    tags: ["واقعیت-مجازی", "رباتیک"],
    collaborators: ["3", "7"],
    progress: 19,
    status: "in-progress",
    started_at: 1660071600000,
    deadline: 1691607600000,
  },
  {
    project_id: "2",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "اچ‌پی",
    project_name: "ویژوال‌داده",
    project_desc:
      "ابزاری برای ساخت داده‌نماها و داشبوردهای تعاملی",
    tags: ["آموزش-فناوری-اطلاعات", "واقعیت-افزوده", "هوش-مصنوعی"],
    collaborators: ["1", "9", "4"],
    progress: 64,
    status: "in-progress",
    started_at: 1668279600000,
    deadline: 1670871600000,
  },
  {
    project_id: "3",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "سونی",
    project_name: "خانه‌هوشمند",
    project_desc:
      "سامانه‌ای برای کنترل و پایش دستگاه‌های هوشمند منزل",
    tags: ["توسعه-وب", "واقعیت-مجازی", "علم-داده"],
    collaborators: ["15", "14", "13", "12", "11"],
    progress: 12,
    status: "in-progress",
    started_at: 1679684400000,
    deadline: 1708801200000,
  },
  {
    project_id: "4",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "لنوو",
    project_name: "امنیت-سایبری",
    project_desc:
      "سامانه‌ای برای کنترل و پایش دستگاه‌های هوشمند منزل",
    tags: ["بلاکچین", "رباتیک"],
    collaborators: ["10"],
    progress: 0,
    status: "pending",
    started_at: 1673031600000,
    deadline: 1694026800000,
  },
  {
    project_id: "5",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "هوآوی",
    project_name: "چت‌بات",
    project_desc: "ربات گفتگوگر که به سوالات پاسخ می‌دهد و کمک‌رسانی می‌کند",
    tags: ["مشاوره-فناوری-اطلاعات", "اینترنت-اشیا"],
    collaborators: ["9", "8"],
    progress: 86,
    status: "in-progress",
    started_at: 1668798000000,
    deadline: 1697655600000,
  },
  {
    project_id: "6",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "اپل",
    project_name: "هوش‌مصنوعی",
    project_desc:
      "سامانه هوش مصنوعی که قادر به شناسایی و پاسخ به دستورات صوتی است",
    tags: ["طراحی-رابط-کاربری"],
    collaborators: ["7", "6", "5", "4"],
    progress: 100,
    status: "done",
    started_at: 1654887600000,
    deadline: 1660158000000,
  },
  {
    project_id: "7",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "ایسر",
    project_name: "توسعه-وب",
    project_desc:
      "سازنده وب‌سایتی که به شما اجازه ساخت و میزبانی سایت خودتان را می‌دهد",
    tags: ["اتوماسیون", "اینترنت-اشیا"],
    collaborators: ["1", "5"],
    progress: 61,
    status: "in-progress",
    started_at: 1652900400000,
    deadline: 1684436400000,
  },
  {
    project_id: "8",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "هوآوی",
    project_name: "ابری",
    project_desc:
      "خدمات رایانش ابری شامل ذخیره‌سازی، محاسبات و منابع شبکه‌ای",
    tags: ["یادگیری-ماشین", "اتوماسیون"],
    collaborators: ["6"],
    progress: 77,
    status: "in-progress",
    started_at: 1660330800000,
    deadline: 1670871600000,
  },
  {
    project_id: "9",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "سونی",
    project_name: "واقعیت‌مجازی",
    project_desc:
      "اپلیکیشن واقعیت مجازی برای کاوش و ساخت محیط‌های فراگیر",
    tags: ["اتوماسیون", "بازی", "علم-داده"],
    collaborators: ["5", "4", "6"],
    progress: 8,
    status: "in-progress",
    started_at: 1670007600000,
    deadline: 1685732400000,
  },
  {
    project_id: "10",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "سونی",
    project_name: "اینترنتیزه",
    project_desc: "دستگاهی که هر شی را به اینترنت اشیا متصل می‌کند",
    tags: ["مدیریت-سامانه"],
    collaborators: ["7", "6", "10"],
    progress: 77,
    status: "in-progress",
    started_at: 1662145200000,
    deadline: 1688324400000,
  },
  {
    project_id: "11",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "اچ‌پی",
    project_name: "زیست‌فناوری",
    project_desc:
      "پروژه زیست‌فناوری با بهره‌گیری از موجودات زنده یا اجزای آن‌ها برای اهداف گوناگون",
    tags: ["توسعه-وب", "مدیریت-سامانه"],
    collaborators: ["11", "12", "13", "14"],
    progress: 14,
    status: "in-progress",
    started_at: 1665687600000,
    deadline: 1689274800000,
  },
  {
    project_id: "12",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "دل",
    project_name: "بازی‌آن",
    project_desc:
      "استودیوی ساخت بازی جهت تولید و انتشار بازی‌های ویدیویی",
    tags: ["توسعه-وب"],
    collaborators: ["15", "1"],
    progress: 5,
    status: "in-progress",
    started_at: 1659639600000,
    deadline: 1685905200000,
  },
  {
    project_id: "13",
    partner_image: "/images/logos/google.svg",
    partner_name: "اچ‌پی",
    project_name: "آموزش‌فناوری",
    project_desc:
      "پروژه فناوری آموزشی جهت بهبود یادگیری و آموزش",
    tags: ["آموزش-فناوری-اطلاعات", "توسعه-اپلیکیشن-موبایل"],
    collaborators: ["14", "13", "12"],
    progress: 58,
    status: "in-progress",
    started_at: 1665169200000,
    deadline: 1678215600000,
  },
  {
    project_id: "14",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "ال‌جی",
    project_name: "فین‌تک",
    project_desc:
      "پروژه فناوری مالی برای ارائه راهکارهای نوآورانه بانکی و مالی",
    tags: ["توسعه-وب"],
    collaborators: ["10"],
    progress: 20,
    status: "in-progress",
    started_at: 1671217200000,
    deadline: 1694890800000,
  },
  {
    project_id: "15",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "لنوو",
    project_name: "فناوری‌سلامت",
    project_desc:
      "پروژه فناوری اطلاعات سلامت با هدف بهبود ارائه و نتایج خدمات درمانی",
    tags: ["امنیت-سایبری", "بلاکچین", "هوش-مصنوعی"],
    collaborators: ["9", "8", "7", "6"],
    progress: 54,
    status: "in-progress",
    started_at: 1673722800000,
    deadline: 1694718000000,
  },
  {
    project_id: "16",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "مایکروسافت",
    project_name: "فناوری‌سبز",
    project_desc:
      "پروژه رمزارز مبتنی بر بلاکچین با امنیت بالا برای تراکنش‌ها",
    tags: ["بلاکچین", "هوش-مصنوعی", "طراحی-رابط-کاربری"],
    collaborators: ["5", "4", "3", "2"],
    progress: 2,
    status: "in-progress",
    started_at: 1652382000000,
    deadline: 1676228400000,
  },
  {
    project_id: "17",
    partner_image: "/images/logos/google.svg",
    partner_name: "سامسونگ",
    project_name: "شبکه‌اجتماعی",
    project_desc:
      "پروژه فناوری زیست محیطی جهت ترویج پایداری و کاهش آثار مخرب محیط زیست",
    tags: ["طراحی-گرافیک"],
    collaborators: ["1"],
    progress: 90,
    status: "in-progress",
    started_at: 1653591600000,
    deadline: 1685127600000,
  },
  {
    project_id: "18",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "هوآوی",
    project_name: "تجارت‌الکترونیک",
    project_desc:
      "پروژه شبکه اجتماعی متصل‌کننده انسان‌ها و جوامع",
    tags: ["تجارت-الکترونیک"],
    collaborators: ["15", "14"],
    progress: 37,
    status: "in-progress",
    started_at: 1661022000000,
    deadline: 1666292400000,
  },
  {
    project_id: "19",
    partner_image: "/images/logos/google.svg",
    partner_name: "هوآوی",
    project_name: "آزمایشگاه‌رسانه",
    project_desc:
      "پروژه تجارت الکترونیک برای فروش محصولات یا خدمات آنلاین",
    tags: ["یادگیری-ماشین", "طراحی-رابط-کاربری"],
    collaborators: ["13", "12", "11", "10"],
    progress: 50,
    status: "in-progress",
    started_at: 1656270000000,
    deadline: 1687806000000,
  },
  {
    project_id: "20",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "اپل",
    project_name: "کُداکس",
    project_desc:
      "پروژه تولید و انتشار محتوای دیجیتال",
    tags: ["امنیت-سایبری", "طراحی-تجربه-کاربری", "پشتیبانی-فنی"],
    collaborators: ["9", "8", "7", "6"],
    progress: 48,
    status: "in-progress",
    started_at: 1664650800000,
    deadline: 1669921200000,
  },
  {
    project_id: "21",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "اچ‌پی",
    project_name: "ویژوال‌داده",
    project_desc: "پلتفرمی برای برنامه‌نویسی و اشکال‌زدایی مشارکتی",
    tags: ["امنیت-سایبری", "بازاریابی-دیجیتال", "بلاکچین"],
    collaborators: ["5", "4", "3", "2"],
    progress: 89,
    status: "in-progress",
    started_at: 1672858800000,
    deadline: 1704394800000,
  },
  {
    project_id: "22",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "ایسر",
    project_name: "خانه‌هوشمند",
    project_desc:
      "ابزاری برای ساخت داده‌نماها و داشبوردهای تعاملی",
    tags: ["رسانه-اجتماعی", "ممیزی-فناوری-اطلاعات", "امنیت-سایبری"],
    collaborators: ["1", "2", "3"],
    progress: 63,
    status: "in-progress",
    started_at: 1661194800000,
    deadline: 1684782000000,
  },
  {
    project_id: "23",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "ریزر",
    project_name: "امنیت-سایبری",
    project_desc:
      "سامانه‌ای برای کنترل و پایش دستگاه‌های هوشمند منزل",
    tags: ["راهبری-فناوری-اطلاعات-و-استراتژی", "علم-داده"],
    collaborators: ["4"],
    progress: 94,
    status: "in-progress",
    started_at: 1666724400000,
    deadline: 1685041200000,
  },
  {
    project_id: "24",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "نینتندو",
    project_name: "چت‌بات",
    project_desc:
      "سامانه‌ای برای کنترل و پایش دستگاه‌های هوشمند منزل",
    tags: ["علم-داده", "رایانش-ابری", "واقعیت-مجازی"],
    collaborators: ["5", "6"],
    progress: 86,
    status: "in-progress",
    started_at: 1661886000000,
    deadline: 1669748400000,
  },
  {
    project_id: "25",
    partner_image: "/images/logos/google.svg",
    partner_name: "اپل",
    project_name: "هوش‌مصنوعی",
    project_desc: "چت‌باتی که به سوالات پاسخ می‌دهد و کمک‌رسانی می‌کند",
    tags: ["مهندسی-نرم‌افزار", "اینترنت-اشیا", "اتوماسیون"],
    collaborators: ["5", "6", "7", "8"],
    progress: 34,
    status: "in-progress",
    started_at: 1663786800000,
    deadline: 1687374000000,
  },
  {
    project_id: "26",
    partner_image: "/images/logos/google.svg",
    partner_name: "ایسر",
    project_name: "توسعه-وب",
    project_desc:
      "سامانه هوش مصنوعی که قادر به شناسایی و پاسخ به دستورات صوتی است",
    tags: ["امنیت-سایبری", "مدیریت-سامانه", "رایانش-ابری"],
    collaborators: ["9"],
    progress: 33,
    status: "in-progress",
    started_at: 1655838000000,
    deadline: 1684695600000,
  },
  {
    project_id: "27",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "مایکروسافت",
    project_name: "ابری",
    project_desc:
      "سازنده وب‌سایتی که به شما اجازه ساخت و میزبانی سایت خودتان را می‌دهد",
    tags: ["پژوهش-فناوری-اطلاعات", "واقعیت-مجازی"],
    collaborators: ["10"],
    progress: 62,
    status: "in-progress",
    started_at: 1657911600000,
    deadline: 1671130800000,
  },
  {
    project_id: "28",
    partner_image: "/images/logos/google.svg",
    partner_name: "اچ‌پی",
    project_name: "واقعیت‌مجازی",
    project_desc:
      "خدمات رایانش ابری شامل ذخیره‌سازی، محاسبات و منابع شبکه‌ای",
    tags: ["یادگیری-ماشین", "واقعیت-مجازی", "اتوماسیون"],
    collaborators: ["11", "12", "13"],
    progress: 15,
    status: "in-progress",
    started_at: 1664564400000,
    deadline: 1669834800000,
  },
  {
    project_id: "29",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "لاجیتک",
    project_name: "اینترنتیزه",
    project_desc:
      "اپلیکیشن واقعیت مجازی برای کاوش و ساخت محیط‌های فراگیر",
    tags: ["واقعیت-مجازی"],
    collaborators: ["14", "15", "1"],
    progress: 44,
    status: "in-progress",
    started_at: 1654282800000,
    deadline: 1683140400000,
  },
  {
    project_id: "30",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "مایکروسافت",
    project_name: "زیست‌فناوری",
    project_desc: "دستگاهی که هر شی را به اینترنت اشیا متصل می‌کند",
    tags: [
      "مشاوره-فناوری-اطلاعات",
      "رایانش-ابری",
      "راهبری-فناوری-اطلاعات-و-استراتژی",
    ],
    collaborators: ["2", "3", "4"],
    progress: 77,
    status: "in-progress",
    started_at: 1664737200000,
    deadline: 1667415600000,
  },
  {
    project_id: "31",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "هوآوی",
    project_name: "بازی‌آن",
    project_desc:
      "پروژه زیست‌فناوری با بهره‌گیری از موجودات زنده یا اجزای آن‌ها برای اهداف گوناگون",
    tags: ["طراحی-رابط-کاربری", "تجربه-کاربری", "آموزش-فناوری-اطلاعات"],
    collaborators: ["5", "6", "7"],
    progress: 86,
    status: "in-progress",
    started_at: 1673031600000,
    deadline: 1688670000000,
  },
  {
    project_id: "32",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "اپل",
    project_name: "آموزش‌فناوری",
    project_desc:
      "استودیوی ساخت بازی جهت تولید و انتشار بازی‌های ویدیویی",
    tags: ["واقعیت-افزوده"],
    collaborators: ["8", "9", "10"],
    progress: 10,
    status: "in-progress",
    started_at: 1662145200000,
    deadline: 1693681200000,
  },
  {
    project_id: "33",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "سامسونگ",
    project_name: "فین‌تک",
    project_desc:
      "پروژه فناوری آموزشی جهت بهبود یادگیری و آموزش",
    tags: ["بازی", "اینترنت-اشیا", "توسعه-اپلیکیشن-موبایل"],
    collaborators: ["11"],
    progress: 9,
    status: "in-progress",
    started_at: 1652468400000,
    deadline: 1657738800000,
  },
  {
    project_id: "34",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "سونی",
    project_name: "فناوری‌سلامت",
    project_desc:
      "پروژه فناوری مالی برای ارائه راهکارهای نوآورانه بانکی و مالی",
    tags: [
      "طراحی-رابط-کاربری",
      "بازاریابی-دیجیتال",
      "مدیریت-سامانه",
    ],
    collaborators: ["12"],
    progress: 71,
    status: "in-progress",
    started_at: 1658170800000,
    deadline: 1676746800000,
  },
  {
    project_id: "35",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Acer",
    project_name: "GreenIT",
    project_desc:
      "A health information technology project that improves health care delivery and outcomes",
    tags: ["it-education", "it-consulting"],
    collaborators: ["13", "14", "15"],
    progress: 8,
    status: "in-progress",
    started_at: 1659553200000,
    deadline: 1691089200000,
  },
  {
    project_id: "36",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Sony",
    project_name: "SocialNet",
    project_desc:
      "A cryptocurrency project that uses blockchain technology for secure transactions",
    tags: ["mobile-app-development", "it-audit", "system-administration"],
    collaborators: ["1", "2", "3"],
    progress: 65,
    status: "in-progress",
    started_at: 1652382000000,
    deadline: 1673550000000,
  },
  {
    project_id: "37",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Sony",
    project_name: "Ecom",
    project_desc:
      "An environmental technology project that promotes sustainability and reduces environmental impact",
    tags: ["e-commerce"],
    collaborators: ["4", "5", "6"],
    progress: 34,
    status: "in-progress",
    started_at: 1657998000000,
    deadline: 1684263600000,
  },
  {
    project_id: "38",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Asus",
    project_name: "MediaLab",
    project_desc:
      "A social networking project that connects people and communities",
    tags: ["social-media", "it-consulting"],
    collaborators: ["7", "8", "9", "10"],
    progress: 48,
    status: "in-progress",
    started_at: 1674327600000,
    deadline: 1697914800000,
  },
  {
    project_id: "39",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Sony",
    project_name: "CodeX",
    project_desc:
      "An e-commerce project that sells products or services online",
    tags: ["internet-of-things", "blockchain", "it-consulting"],
    collaborators: ["11"],
    progress: 80,
    status: "in-progress",
    started_at: 1671390000000,
    deadline: 1700334000000,
  },
  {
    project_id: "40",
    partner_image: "/images/logos/google.svg",
    partner_name: "Razer",
    project_name: "DataViz",
    project_desc:
      "A media production project that creates and distributes digital content",
    tags: ["it-research"],
    collaborators: ["12", "13", "14", "15"],
    progress: 55,
    status: "in-progress",
    started_at: 1667242800000,
    deadline: 1680289200000,
  },
  {
    project_id: "41",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "LG",
    project_name: "SmartHome",
    project_desc: "A platform for collaborative coding and debugging",
    tags: ["graphic-design"],
    collaborators: ["1"],
    progress: 8,
    status: "in-progress",
    started_at: 1674327600000,
    deadline: 1687374000000,
  },
  {
    project_id: "42",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Sony",
    project_name: "CyberSec",
    project_desc:
      "A tool for creating interactive data visualizations and dashboards",
    tags: ["gaming", "web-development", "robotics"],
    collaborators: ["2", "3"],
    progress: 80,
    status: "in-progress",
    started_at: 1680375600000,
    deadline: 1709319600000,
  },
  {
    project_id: "43",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Lenovo",
    project_name: "ChatBot",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["cybersecurity"],
    collaborators: ["4", "6", "5"],
    progress: 54,
    status: "in-progress",
    started_at: 1682535600000,
    deadline: 1687806000000,
  },
  {
    project_id: "44",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Huawei",
    project_name: "AIr",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["user-interface-design"],
    collaborators: ["7", "8", "9", "10"],
    progress: 55,
    status: "in-progress",
    started_at: 1674932400000,
    deadline: 1690570800000,
  },
  {
    project_id: "45",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Samsung",
    project_name: "WebDev",
    project_desc: "A chatbot that can answer questions and provide assistance",
    tags: ["user-experience-design"],
    collaborators: ["11", "12", "13", "14", "15"],
    progress: 85,
    status: "in-progress",
    started_at: 1652986800000,
    deadline: 1681930800000,
  },
  {
    project_id: "46",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Nintendo",
    project_name: "Cloudy",
    project_desc:
      "An artificial intelligence system that can recognize and respond to voice commands",
    tags: ["gaming", "it-education", "virtual-reality"],
    collaborators: ["1", "2", "3", "4", "5"],
    progress: 48,
    status: "in-progress",
    started_at: 1677351600000,
    deadline: 1703530800000,
  },
  {
    project_id: "47",
    partner_image: "/images/logos/google.svg",
    partner_name: "Apple",
    project_name: "VRy",
    project_desc:
      "A website builder that lets you create and host your own websites",
    tags: ["augmented-reality"],
    collaborators: ["6", "7", "8"],
    progress: 69,
    status: "in-progress",
    started_at: 1659812400000,
    deadline: 1665082800000,
  },
  {
    project_id: "48",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Samsung",
    project_name: "IoTize",
    project_desc:
      "A cloud computing service that offers storage & computing and networking resources",
    tags: ["e-commerce"],
    collaborators: ["10", "9", "11", "12", "13"],
    progress: 46,
    status: "in-progress",
    started_at: 1678906800000,
    deadline: 1681585200000,
  },
  {
    project_id: "49",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Razer",
    project_name: "BioTech",
    project_desc:
      "A virtual reality app that lets you explore and create immersive environments",
    tags: ["it-research"],
    collaborators: ["14", "15", "1", "2"],
    progress: 8,
    status: "in-progress",
    started_at: 1667588400000,
    deadline: 1688497200000,
  },
  {
    project_id: "50",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Apple",
    project_name: "GameOn",
    project_desc: "A device that connects any object to the internet of things",
    tags: ["user-experience-design"],
    collaborators: ["3", "4"],
    progress: 56,
    status: "in-progress",
    started_at: 1675105200000,
    deadline: 1685473200000,
  },
  {
    project_id: "51",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Samsung",
    project_name: "EduTech",
    project_desc:
      "A biotechnology project that uses living organisms or their components for various purposes",
    tags: ["robotics", "cloud-computing"],
    collaborators: ["5", "6"],
    progress: 35,
    status: "in-progress",
    started_at: 1652554800000,
    deadline: 1684090800000,
  },
  {
    project_id: "52",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Samsung",
    project_name: "FinTech",
    project_desc:
      "A game development studio that creates and publishes video games",
    tags: ["blockchain"],
    collaborators: ["7", "8", "9"],
    progress: 74,
    status: "in-progress",
    started_at: 1655492400000,
    deadline: 1663441200000,
  },
  {
    project_id: "53",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Razer",
    project_name: "HealthIT",
    project_desc:
      "An educational technology project that enhances learning and teaching",
    tags: ["database-management"],
    collaborators: ["10", "11"],
    progress: 69,
    status: "in-progress",
    started_at: 1660244400000,
    deadline: 1665514800000,
  },
  {
    project_id: "54",
    partner_image: "/images/logos/google.svg",
    partner_name: "HP",
    project_name: "GreenIT",
    project_desc:
      "A financial technology project that provides innovative solutions for banking and finance",
    tags: ["it-research", "robotics", "mobile-app-development"],
    collaborators: ["12", "13", "14", "15"],
    progress: 76,
    status: "in-progress",
    started_at: 1671822000000,
    deadline: 1698087600000,
  },
  {
    project_id: "55",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Microsoft",
    project_name: "SocialNet",
    project_desc:
      "A health information technology project that improves health care delivery and outcomes",
    tags: ["software-engineering", "automation"],
    collaborators: ["1", "2"],
    progress: 9,
    status: "in-progress",
    started_at: 1656356400000,
    deadline: 1661626800000,
  },
  {
    project_id: "56",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "LG",
    project_name: "Ecom",
    project_desc:
      "A cryptocurrency project that uses blockchain technology for secure transactions",
    tags: ["robotics", "graphic-design"],
    collaborators: ["5"],
    progress: 19,
    status: "in-progress",
    started_at: 1670526000000,
    deadline: 1678302000000,
  },
  {
    project_id: "57",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Sony",
    project_name: "MediaLab",
    project_desc:
      "An environmental technology project that promotes sustainability and reduces environmental impact",
    tags: ["automation"],
    collaborators: ["3", "4"],
    progress: 33,
    status: "in-progress",
    started_at: 1659034800000,
    deadline: 1664391600000,
  },
  {
    project_id: "58",
    partner_image: "/images/logos/google.svg",
    partner_name: "Dell",
    project_name: "CodeX",
    project_desc:
      "A social networking project that connects people and communities",
    tags: ["it-consulting", "graphic-design"],
    collaborators: ["5", "6", "8", "7"],
    progress: 98,
    status: "in-progress",
    started_at: 1681412400000,
    deadline: 1697223600000,
  },
  {
    project_id: "59",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "HP",
    project_name: "DataViz",
    project_desc:
      "An e-commerce project that sells products or services online",
    tags: ["user-interface-design", "software-engineering", "virtual-reality"],
    collaborators: ["10", "11", "12", "13"],
    progress: 29,
    status: "in-progress",
    started_at: 1669662000000,
    deadline: 1698519600000,
  },
  {
    project_id: "60",
    partner_image: "/images/logos/google.svg",
    partner_name: "Sony",
    project_name: "SmartHome",
    project_desc:
      "A media production project that creates and distributes digital content",
    tags: ["database-management", "gaming"],
    collaborators: ["14", "15", "1", "2"],
    progress: 90,
    status: "in-progress",
    started_at: 1677265200000,
    deadline: 1684954800000,
  },
  {
    project_id: "61",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Samsung",
    project_name: "CyberSec",
    project_desc: "A platform for collaborative coding and debugging",
    tags: ["it-governance-and-it-strategy."],
    collaborators: ["3", "4"],
    progress: 48,
    status: "in-progress",
    started_at: 1664564400000,
    deadline: 1693508400000,
  },
  {
    project_id: "62",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Apple",
    project_name: "ChatBot",
    project_desc:
      "A tool for creating interactive data visualizations and dashboards",
    tags: ["it-consulting", "machine-learning"],
    collaborators: ["5", "7", "6"],
    progress: 47,
    status: "in-progress",
    started_at: 1657911600000,
    deadline: 1668538800000,
  },
  {
    project_id: "63",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Samsung",
    project_name: "AIr",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["machine-learning"],
    collaborators: ["8", "9", "10", "11"],
    progress: 41,
    status: "in-progress",
    started_at: 1658516400000,
    deadline: 1663873200000,
  },
  {
    project_id: "64",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Sony",
    project_name: "WebDev",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["it-consulting", "virtual-reality", "social-media"],
    collaborators: ["12", "13"],
    progress: 87,
    status: "in-progress",
    started_at: 1670698800000,
    deadline: 1694372400000,
  },
  {
    project_id: "65",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Samsung",
    project_name: "Cloudy",
    project_desc: "A chatbot that can answer questions and provide assistance",
    tags: ["machine-learning", "database-management", "graphic-design"],
    collaborators: ["14"],
    progress: 20,
    status: "in-progress",
    started_at: 1657134000000,
    deadline: 1678129200000,
  },
  {
    project_id: "66",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Huawei",
    project_name: "VRy",
    project_desc:
      "An artificial intelligence system that can recognize and respond to voice commands",
    tags: ["it-education", "artificial-intelligence"],
    collaborators: ["15", "1"],
    progress: 19,
    status: "in-progress",
    started_at: 1654974000000,
    deadline: 1678561200000,
  },
  {
    project_id: "67",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Apple",
    project_name: "IoTize",
    project_desc:
      "A website builder that lets you create and host your own websites",
    tags: ["robotics", "digital-marketing", "user-experience-design"],
    collaborators: ["1", "2", "3"],
    progress: 45,
    status: "in-progress",
    started_at: 1668625200000,
    deadline: 1697482800000,
  },
  {
    project_id: "68",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Samsung",
    project_name: "BioTech",
    project_desc:
      "A cloud computing service that offers storage & computing and networking resources",
    tags: ["cybersecurity"],
    collaborators: ["4", "5", "6", "7"],
    progress: 28,
    status: "in-progress",
    started_at: 1658343600000,
    deadline: 1666292400000,
  },
  {
    project_id: "69",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "LG",
    project_name: "GameOn",
    project_desc:
      "A virtual reality app that lets you explore and create immersive environments",
    tags: ["data-science"],
    collaborators: ["8"],
    progress: 48,
    status: "in-progress",
    started_at: 1668711600000,
    deadline: 1694977200000,
  },
  {
    project_id: "70",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Dell",
    project_name: "EduTech",
    project_desc: "A device that connects any object to the internet of things",
    tags: ["technical-support", "machine-learning", "system-administration"],
    collaborators: ["9", "10", "11", "12"],
    progress: 34,
    status: "in-progress",
    started_at: 1675191600000,
    deadline: 1688151600000,
  },
  {
    project_id: "71",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Asus",
    project_name: "FinTech",
    project_desc:
      "A biotechnology project that uses living organisms or their components for various purposes",
    tags: ["technical-support"],
    collaborators: ["13", "14", "15", "2"],
    progress: 29,
    status: "in-progress",
    started_at: 1677351600000,
    deadline: 1708887600000,
  },
  {
    project_id: "72",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Lenovo",
    project_name: "HealthIT",
    project_desc:
      "A game development studio that creates and publishes video games",
    tags: ["social-media", "cybersecurity", "software-engineering"],
    collaborators: ["1"],
    progress: 59,
    status: "in-progress",
    started_at: 1673031600000,
    deadline: 1688670000000,
  },
  {
    project_id: "73",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Acer",
    project_name: "GreenIT",
    project_desc:
      "An educational technology project that enhances learning and teaching",
    tags: ["user-interface-design"],
    collaborators: ["2", "3", "4"],
    progress: 60,
    status: "in-progress",
    started_at: 1661799600000,
    deadline: 1688065200000,
  },
  {
    project_id: "74",
    partner_image: "/images/logos/google.svg",
    partner_name: "Samsung",
    project_name: "SocialNet",
    project_desc:
      "A financial technology project that provides innovative solutions for banking and finance",
    tags: ["virtual-reality", "system-administration", "gaming"],
    collaborators: ["5", "6", "7"],
    progress: 50,
    status: "in-progress",
    started_at: 1671044400000,
    deadline: 1694718000000,
  },
  {
    project_id: "75",
    partner_image: "/images/logos/google.svg",
    partner_name: "Nintendo",
    project_name: "Ecom",
    project_desc:
      "A health information technology project that improves health care delivery and outcomes",
    tags: ["it-audit", "it-governance-and-it-strategy."],
    collaborators: ["8", "9"],
    progress: 71,
    status: "in-progress",
    started_at: 1669143600000,
    deadline: 1687460400000,
  },
  {
    project_id: "76",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Sony",
    project_name: "MediaLab",
    project_desc:
      "A cryptocurrency project that uses blockchain technology for secure transactions",
    tags: ["cloud-computing"],
    collaborators: ["10", "11", "12"],
    progress: 93,
    status: "in-progress",
    started_at: 1652727600000,
    deadline: 1663354800000,
  },
  {
    project_id: "77",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Sony",
    project_name: "CodeX",
    project_desc:
      "An environmental technology project that promotes sustainability and reduces environmental impact",
    tags: ["it-consulting", "cybersecurity"],
    collaborators: ["13", "14", "15", "1"],
    progress: 53,
    status: "in-progress",
    started_at: 1678042800000,
    deadline: 1691262000000,
  },
  {
    project_id: "78",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Nintendo",
    project_name: "DataViz",
    project_desc:
      "A social networking project that connects people and communities",
    tags: ["database-management", "virtual-reality"],
    collaborators: ["1", "2", "3"],
    progress: 77,
    status: "in-progress",
    started_at: 1657047600000,
    deadline: 1662404400000,
  },
  {
    project_id: "79",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Sony",
    project_name: "SmartHome",
    project_desc:
      "An e-commerce project that sells products or services online",
    tags: ["user-experience-design"],
    collaborators: ["4"],
    progress: 95,
    status: "in-progress",
    started_at: 1681412400000,
    deadline: 1713034800000,
  },
  {
    project_id: "80",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Razer",
    project_name: "CyberSec",
    project_desc:
      "A media production project that creates and distributes digital content",
    tags: ["user-experience-design", "web-development", "digital-marketing"],
    collaborators: ["5", "6", "7", "8"],
    progress: 2,
    status: "in-progress",
    started_at: 1682881200000,
    deadline: 1714503600000,
  },
  {
    project_id: "81",
    partner_image: "/images/logos/google.svg",
    partner_name: "Acer",
    project_name: "ChatBot",
    project_desc: "A platform for collaborative coding and debugging",
    tags: ["digital-marketing", "robotics", "it-education"],
    collaborators: ["9", "10", "11", "12"],
    progress: 37,
    status: "in-progress",
    started_at: 1676228400000,
    deadline: 1694545200000,
  },
  {
    project_id: "82",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Sony",
    project_name: "AIr",
    project_desc:
      "A tool for creating interactive data visualizations and dashboards",
    tags: ["machine-learning", "e-commerce"],
    collaborators: ["14"],
    progress: 41,
    status: "in-progress",
    started_at: 1668538800000,
    deadline: 1692126000000,
  },
  {
    project_id: "83",
    partner_image: "/images/logos/behance-round.svg",
    partner_name: "Acer",
    project_name: "WebDev",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["blockchain"],
    collaborators: ["1", "2"],
    progress: 31,
    status: "in-progress",
    started_at: 1654110000000,
    deadline: 1669921200000,
  },
  {
    project_id: "84",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Acer",
    project_name: "Cloudy",
    project_desc:
      "A system for controlling and monitoring smart devices in your home",
    tags: ["robotics", "system-administration"],
    collaborators: ["3", "4", "5"],
    progress: 50,
    status: "in-progress",
    started_at: 1669921200000,
    deadline: 1688238000000,
  },
  {
    project_id: "85",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Acer",
    project_name: "VRy",
    project_desc: "A chatbot that can answer questions and provide assistance",
    tags: ["robotics", "technical-support", "it-governance-and-it-strategy."],
    collaborators: ["6", "7"],
    progress: 12,
    status: "in-progress",
    started_at: 1678820400000,
    deadline: 1707937200000,
  },
  {
    project_id: "86",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Samsung",
    project_name: "IoTize",
    project_desc:
      "An artificial intelligence system that can recognize and respond to voice commands",
    tags: [
      "user-interface-design",
      "software-engineering",
      "artificial-intelligence",
    ],
    collaborators: ["8", "9", "10", "11"],
    progress: 83,
    status: "in-progress",
    started_at: 1682449200000,
    deadline: 1692990000000,
  },
  {
    project_id: "87",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Huawei",
    project_name: "BioTech",
    project_desc:
      "A website builder that lets you create and host your own websites",
    tags: ["artificial-intelligence"],
    collaborators: ["11", "12", "13"],
    progress: 13,
    status: "in-progress",
    started_at: 1682881200000,
    deadline: 1709233200000,
  },
  {
    project_id: "88",
    partner_image: "/images/logos/google.svg",
    partner_name: "Apple",
    project_name: "GameOn",
    project_desc:
      "A cloud computing service that offers storage & computing and networking resources",
    tags: ["user-interface-design", "database-management"],
    collaborators: ["14", "15", "1", "3"],
    progress: 9,
    status: "in-progress",
    started_at: 1656874800000,
    deadline: 1675450800000,
  },
  {
    project_id: "89",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Razer",
    project_name: "EduTech",
    project_desc:
      "A virtual reality app that lets you explore and create immersive environments",
    tags: ["technical-support"],
    collaborators: ["1", "2", "3", "4"],
    progress: 27,
    status: "in-progress",
    started_at: 1663095600000,
    deadline: 1665687600000,
  },
  {
    project_id: "90",
    partner_image: "/images/logos/google.svg",
    partner_name: "Nintendo",
    project_name: "FinTech",
    project_desc: "A device that connects any object to the internet of things",
    tags: ["it-consulting", "software-engineering"],
    collaborators: ["1", "2", "3"],
    progress: 38,
    status: "in-progress",
    started_at: 1653073200000,
    deadline: 1661022000000,
  },
  {
    project_id: "91",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "HP",
    project_name: "HealthIT",
    project_desc:
      "A biotechnology project that uses living organisms or their components for various purposes",
    tags: ["network-administration", "internet-of-things"],
    collaborators: ["5"],
    progress: 66,
    status: "in-progress",
    started_at: 1661281200000,
    deadline: 1692817200000,
  },
  {
    project_id: "92",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "LG",
    project_name: "GreenIT",
    project_desc:
      "A game development studio that creates and publishes video games",
    tags: ["internet-of-things", "automation"],
    collaborators: ["6"],
    progress: 93,
    status: "in-progress",
    started_at: 1658948400000,
    deadline: 1664305200000,
  },
  {
    project_id: "93",
    partner_image: "/images/logos/google.svg",
    partner_name: "Huawei",
    project_name: "SocialNet",
    project_desc:
      "An educational technology project that enhances learning and teaching",
    tags: ["database-management", "technical-support"],
    collaborators: ["7"],
    progress: 96,
    status: "in-progress",
    started_at: 1668884400000,
    deadline: 1681930800000,
  },
  {
    project_id: "94",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Lenovo",
    project_name: "Ecom",
    project_desc:
      "A financial technology project that provides innovative solutions for banking and finance",
    tags: ["graphic-design", "cloud-computing"],
    collaborators: ["5", "15", "14", "13"],
    progress: 97,
    status: "in-progress",
    started_at: 1655492400000,
    deadline: 1676660400000,
  },
  {
    project_id: "95",
    partner_image: "/images/logos/adobe_portfolio-round.svg",
    partner_name: "Dell",
    project_name: "MediaLab",
    project_desc:
      "A health information technology project that improves health care delivery and outcomes",
    tags: ["it-audit"],
    collaborators: ["12", "11", "10"],
    progress: 28,
    status: "in-progress",
    started_at: 1678302000000,
    deadline: 1707418800000,
  },
  {
    project_id: "96",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Dell",
    project_name: "CodeX",
    project_desc:
      "A cryptocurrency project that uses blockchain technology for secure transactions",
    tags: ["mobile-app-development"],
    collaborators: ["9", "8", "7", "6"],
    progress: 9,
    status: "in-progress",
    started_at: 1682535600000,
    deadline: 1706295600000,
  },
  {
    project_id: "97",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Asus",
    project_name: "DataViz",
    project_desc:
      "An environmental technology project that promotes sustainability and reduces environmental impact",
    tags: ["cybersecurity", "database-management", "cloud-computing"],
    collaborators: ["5"],
    progress: 89,
    status: "in-progress",
    started_at: 1666638000000,
    deadline: 1695582000000,
  },
  {
    project_id: "98",
    partner_image: "/images/logos/microsoft.svg",
    partner_name: "Sony",
    project_name: "SmartHome",
    project_desc:
      "A social networking project that connects people and communities",
    tags: ["it-governance-and-it-strategy.", "system-administration"],
    collaborators: ["4", "3", "2", "1"],
    progress: 79,
    status: "in-progress",
    started_at: 1678215600000,
    deadline: 1704654000000,
  },
  {
    project_id: "99",
    partner_image: "/images/logos/pinterest-round.svg",
    partner_name: "Microsoft",
    project_name: "CyberSec",
    project_desc:
      "An e-commerce project that sells products or services online",
    tags: ["it-consulting"],
    collaborators: ["15", "14", "13", "12"],
    progress: 53,
    status: "in-progress",
    started_at: 1677610800000,
    deadline: 1682881200000,
  },
  {
    project_id: "100",
    partner_image: "/images/logos/flickr-round.svg",
    partner_name: "Nintendo",
    project_name: "ChatBot",
    project_desc:
      "A media production project that creates and distributes digital content",
    tags: ["web-development", "user-interface-design"],
    collaborators: ["11", "10"],
    progress: 92,
    status: "in-progress",
    started_at: 1673809200000,
    deadline: 1689447600000,
  },
];

export const collaborators: Collaborator[] = [
  {
    uid: "1",
    name: "Hossein",
    avatar: undefined,
  },
  {
    uid: "2",
    name: "امیلیا کلارک",
    avatar: "/images/avatar/avatar-11.jpg",
  },
  {
    uid: "3",
    name: "مجید یحیایی",
    avatar: "/images/avatar/avatar-20.jpg",
  },
  {
    uid: "4",
    name: "Amir",
    avatar: undefined,
  },
  {
    uid: "5",
    name: "آلفردو الیوت",
    avatar: "/images/avatar/avatar-4.jpg",
  },
  {
    uid: "6",
    name: "Ahmad",
    avatar: undefined,
  },
  {
    uid: "7",
    name: "Reza",
    avatar: undefined,
  },
  {
    uid: "8",
    name: "مت ریوز",
    avatar: "/images/avatar/avatar-3.jpg",
  },
  {
    uid: "9",
    name: "تیموتی شالامی",
    avatar: "/images/avatar/avatar-2.jpg",
  },
  {
    uid: "10",
    name: "لنس تاکر",
    avatar: "/images/avatar/avatar-18.jpg",
  },
  {
    uid: "11",
    name: "کاترینا وست",
    avatar: "/images/avatar/avatar-11.jpg",
  },
  {
    uid: "12",
    name: "سامانتا شلتون",
    avatar: "/images/avatar/avatar-11.jpg",
  },
  {
    uid: "13",
    name: "کوری ایوانز",
    avatar: "/images/avatar/avatar-1.jpg",
  },
  {
    uid: "14",
    name: "جو پرکینز",
    avatar: "/images/avatar/avatar-5.jpg",
  },
  {
    uid: "15",
    name: "Mehdi",
    avatar: undefined,
  },
];

export const tags: Tag[] = [
  { value: "virtual-reality", label: "واقعیت مجازی" },
  { value: "robotics", label: "رباتیک" },
  { value: "it-education", label: "آموزش IT" },
  { value: "augmented-reality", label: "واقعیت افزوده" },
  { value: "artificial-intelligence", label: "هوش مصنوعی" },
  { value: "web-development", label: "توسعه وب" },
  { value: "data-science", label: "علم داده" },
  { value: "blockchain", label: "بلاکچین" },
  { value: "it-consulting", label: "مشاوره IT" },
  { value: "internet-of-things", label: "اینترنت اشیاء" },
  { value: "user-interface-design", label: "طراحی رابط کاربری" },
  { value: "automation", label: "اتوماسیون" },
  { value: "machine-learning", label: "یادگیری ماشین" },
  { value: "gaming", label: "بازی سازی" },
  { value: "system-administration", label: "مدیریت سیستم" },
  { value: "mobile-app-development", label: "توسعه اپلیکیشن موبایل" },
  { value: "cybersecurity", label: "امنیت سایبری" },
  { value: "graphic-design", label: "طراحی گرافیک" },
  { value: "e-commerce", label: "تجارت الکترونیک" },
  { value: "user-experience-design", label: "طراحی تجربه کاربری" },
  { value: "technical-support", label: "پشتیبانی فنی" },
  { value: "digital-marketing", label: "بازاریابی دیجیتال" },
  { value: "social-media", label: "رسانه‌های اجتماعی" },
  { value: "it-audit", label: "ممیزی IT" },
  {
    value: "it-governance-and-it-strategy",
    label: "حاکمیت و استراتژی IT",
  },
  { value: "cloud-computing", label: "رایانش ابری" },
  { value: "software-engineering", label: "مهندسی نرم‌افزار" },
  { value: "it-research", label: "تحقیقات IT" },
  { value: "database-management", label: "مدیریت پایگاه داده" },
  { value: "network-administration", label: "مدیریت شبکه" },
];
